CmdPatternCallbacks.cpp
void display_help()
display help
Referenced by get_help, setup.
void display_help_get()
display help
Referenced by get_help.
void display_help_set()
display help
Referenced by get_help.
void display_help_move()
display help
Referenced by get_help, rotate_cmd.
void display_help_undo()
display help
Referenced by get_help.
void display_help_reset()
display help
Referenced by get_help.
void display_help_sleep()
display help
Referenced by get_help.
void get_help(CmdParser *myParser)
display help
References display_help, display_help_get, display_help_move, display_help_reset, display_help_set, display_help_sleep, display_help_undo, CmdParser::equalCmdParam, myParser.
Referenced by setup.
void get_cmd(CmdParser *myParser)
callback cmd
my cmdParser
References AlignId, CmdStack, DS_x, CmdParser::equalCmdParam, ICommand::execute, M_X, M_Y, M_Z, myParser.
Referenced by setup.
void set_cmd(CmdParser *myParser)
callback cmd
my cmdParser
References AlignId, CmdStack, CmdParser::equalCmdParam, ICommand::execute, CmdParser::getCmdParam, M_X, M_Y, M_Z, myParser.
Referenced by setup.
void move_cmd(CmdParser *myParser)
callback cmd
my cmdParser
References AlignObj, CmdStack, CmdParser::equalCmdParam, ICommand::execute, CmdParser::getCmdParam, M_X, M_Y, M_Z, myParser.
Referenced by setup.
void rotate_cmd(CmdParser *myParser)
callback cmd
my cmdParser
References AlignObj, CmdStack, display_help_move, CmdParser::equalCmdParam, ICommand::execute, CmdParser::getCmdParam, M_X, myParser.
Referenced by setup.
void calibrate_cmd(CmdParser *myParser)
calibrate cmd using invoker
myParser
References AlignObj, CmdParser::equalCmdParam, CmdParser::getCmdParam, myParser, FirmInvoker::SetOnCalibrate.
Referenced by setup.
void reset_cmd(CmdParser *myParser)
reset device
myParser
References ICommand::execute, resetObj.
Referenced by setup.
void sleep_cmd(CmdParser *myParser)
reset device
myParser
References ICommand::execute, sleepObj.
Referenced by setup.
void undo_cmd(CmdParser *myParser)
undo last command by calling undo(), then remove it from stack
undo last command by calling undo();, then remove it from stack myParser
References CmdStack.
Referenced by setup.