endSwitch
bool endSwitch::current_state
Referenced by get_current_state.
bool endSwitch::last_state
bool endSwitch::Ispressed
Referenced by Alignment::MoveHomeAll.
int endSwitch::Pin
Referenced by debounce, endSwitch, get_current_state.
bool endSwitch::PressedState
Referenced by Alignment::checkLimitDownX, Alignment::checkLimitDownY, Alignment::checkLimitDownZ, endSwitch, Alignment::MoveHomeAll.
endSwitch::endSwitch()
endSwitch::endSwitch(int Pin, bool PressedState)
Construct a new end Switch::end Switch object.
Pin
References Pin, PressedState.
bool endSwitch::get_current_state(bool debounceButton=false)
get current state
true false
References current_state, debounce, Pin.
Referenced by Alignment::getReadingEndstopX, Alignment::getReadingEndstopY, Alignment::getReadingEndstopZ, Alignment::isStopButtonPressed, Alignment::MoveHomeAll.
bool endSwitch::debounce()
debounce a button
References Pin.
Referenced by get_current_state.