CmdCallbackObject
Thread* CmdCallbackObject::InternThread
ThreadController* CmdCallbackObject::InternalScheduler
CmdCallFunct* CmdCallbackObject::m_functList
size_t CmdCallbackObject::current_idx
Referenced by _CmdCallback< STORESIZE, T >::callStoreFunct.
bool CmdCallbackObject::CmdreadyForExecution
Thread * CmdCallbackObject::getInternalThread() const
ThreadController * CmdCallbackObject::getInternalScheduler() const
void CmdCallbackObject::createThreadForCmd(CmdParser *cmdParser)
void CmdCallbackObject::processCmdVoid(CmdParser *cmdParser)
References callStoreFunct, checkStorePos, equalStoreCmd, CmdParser::getCommand.
void * CmdCallbackObject::threadCallback(size_t idx, CmdParser *cmdParser)
internal thread callback
cmdParser CmdBuffer void*
void CmdCallbackObject::loopCmdProcessing(CmdParser *cmdParser, CmdBufferObject *cmdBuffer, Stream *serial)
Endless loop for process incoming data from serial. cmdParser Parser object with options set cmdBuffer Buffer object for data handling serial Arduino serial interface from comming data
References CmdBufferObject::clear, CMDPARSER_ERROR, CmdParser::parseCmd, processCmd, CmdBufferObject::readFromSerial.
bool CmdCallbackObject::processCmd(CmdParser *cmdParser)
Search command in the buffer and execute the callback function. cmdStr Cmd string to search TRUE if found the command in the buffer
References callStoreFunct, checkStorePos, equalStoreCmd, CmdParser::getCommand.
Referenced by loopCmdProcessing, updateCmdProcessing.
bool CmdCallbackObject::runCmd(char *cmdStr, CmdParser *cmdParser)
References callStoreFunct, checkStorePos, equalStoreCmd.
void CmdCallbackObject::updateCmdProcessing(CmdParser *cmdParser, CmdBufferObject *cmdBuffer, Stream *serial)
Check for single new char on serial and if it was the endChar cmdParser Parser object with options set cmdBuffer Buffer object for data handling serial Arduino serial interface from comming data
References CmdBufferObject::clear, CMDPARSER_ERROR, CmdParser::parseCmd, processCmd, CmdBufferObject::readSerialChar.
bool CmdCallbackObject::hasCmd(char *cmdStr)
Search command in the buffer. cmdStr Cmd string to search TRUE if found the command in the buffer
References checkStorePos, equalStoreCmd.
virtual size_t CmdCallbackObject::getStoreSize()=0
Give the size of callback store. Size of callback Store
virtual bool CmdCallbackObject::checkStorePos(size_t idx)=0
Check is on store idx a valide cmd string and function. idx Store number TRUE if valid or FALSE
Referenced by hasCmd, processCmd, processCmdVoid, runCmd.
virtual bool CmdCallbackObject::equalStoreCmd(size_t idx, char *cmdStr)=0
Check if the cmd string equal to cmd in store. Please check idx with checkStorePos befor you use this funct! idx Store number cmdStr Cmd string to search TRUE is equal
Referenced by hasCmd, processCmd, processCmdVoid, runCmd.
virtual bool CmdCallbackObject::callStoreFunct(size_t idx, CmdParser *cmdParser)=0
Call function from store. Please check idx with checkStorePos befor you use this funct! idx Store number TRUE if function is valid and calling
Referenced by processCmd, processCmdVoid, runCmd.