Alignment
Nema8* Alignment::Motor_x
Referenced by AlignLoop, Alignment, CheckBoundaryX, DisableAll, EnableAll, GoToReferenceUp, incrementTotalStepCounted, InitAlign, MoveAngleAllSafe, MoveAngleX, MoveAngleXSafe, MoveDistanceAllSafe, MoveDistanceMSafe, MoveDistanceX, MoveDistanceXloop, MoveDistanceXSafe, MoveDown, MoveDownTo, MoveHomeAll, MoveUp, MoveUpTo, resetStepCounter, StepOnceX.
Nema8* Alignment::Motor_y
Referenced by AlignLoop, Alignment, DisableAll, EnableAll, GoToReferenceUp, incrementTotalStepCounted, InitAlign, MoveAngleAllSafe, MoveAngleY, MoveAngleYSafe, MoveDistanceAllSafe, MoveDistanceMSafe, MoveDistanceY, MoveDistanceYloop, MoveDistanceYSafe, MoveDown, MoveDownTo, MoveHomeAll, MoveUp, MoveUpTo, resetStepCounter, StepOnceY.
Nema8* Alignment::Motor_z
Referenced by AlignLoop, Alignment, DisableAll, EnableAll, GoToReferenceUp, incrementTotalStepCounted, InitAlign, MoveAngleAllSafe, MoveAngleZ, MoveAngleZSafe, MoveDistanceAllSafe, MoveDistanceMSafe, MoveDistanceZ, MoveDistanceZloop, MoveDistanceZSafe, MoveDown, MoveDownTo, MoveHomeAll, MoveUp, MoveUpTo, resetStepCounter, StepOnceZ.
Nema8* Alignment::Motor_PrintHead
Referenced by Alignment, DisableAll, EnableAll, incrementTotalStepCounted, InitAlign, initFirmwareUnit, movePhToRefX, resetStepCounter, rotateAnglePH, RotateAnglePHloop, StepOncePH.
endSwitch* Alignment::endSwitch_x
Referenced by Alignment, checkLimitDownX, getReadingEndstopX, MoveHomeAll.
endSwitch* Alignment::endSwitch_y
Referenced by Alignment, checkLimitDownY, getReadingEndstopY, MoveHomeAll.
endSwitch* Alignment::endSwitch_z
Referenced by Alignment, checkLimitDownZ, getReadingEndstopZ, MoveHomeAll.
endSwitch* Alignment::endSwitch_stop
Referenced by Alignment, isStopButtonPressed.
lightBarrier* Alignment::lightBarrier_x
Referenced by Alignment, checkLimitUpX, getReadingLightBarrierX, GoToReferenceUp.
lightBarrier* Alignment::lightBarrier_y
Referenced by Alignment, checkLimitUpY, checkLimitUpZ, getReadingLightBarrierY, GoToReferenceUp.
lightBarrier* Alignment::lightBarrier_z
Referenced by Alignment, getReadingLightBarrierZ, GoToReferenceUp.
DistanceSensor* Alignment::DistanceM_x
Referenced by AlignLoop, Alignment, calibratePrintHead, getCurrentPosX, getMinX, getRemainingDistanceX, getValueSensorX, movePhToRefX.
DistanceSensor* Alignment::DistanceM_y
Referenced by AlignLoop, Alignment, calibratePrintHead, getCurrentPosY, getMinY, getRemainingDistanceY, getValueSensorY.
DistanceSensor* Alignment::DistanceM_z
Referenced by AlignLoop, Alignment, calibratePrintHead, getCurrentPosZ, getMinZ, getRemainingDistanceZ, getValueSensorZ.
const float Alignment::MinDistanceToML
const float Alignment::MaxDistanceToMl
float Alignment::TargetDistancePHToMl
Referenced by calibratePrintHead, setTargetDistancePHToML.
float Alignment::TargetDistanceSensorToMl
Referenced by AlignLoop, setTargetDistanceSensorToML.
int Alignment::NumOfCycles
bool Alignment::homed
bool Alignment::aligned
bool Alignment::allDownMax
Referenced by MoveDown.
bool Alignment::xDownMax
Referenced by MoveDown.
bool Alignment::yDownMax
Referenced by MoveDown.
bool Alignment::zDownMax
Referenced by MoveDown.
bool Alignment::allUpMax
Referenced by MoveUp.
bool Alignment::xUpMax
Referenced by MoveUp.
bool Alignment::yUpMax
Referenced by MoveUp.
bool Alignment::zUpMax
Referenced by MoveUp.
bool Alignment::xUpDistanceArrived
Referenced by MoveUpTo.
bool Alignment::yUpDistanceArrived
Referenced by MoveUpTo.
bool Alignment::zUpDistanceArrived
Referenced by MoveUpTo.
bool Alignment::allUpDistanceArrived
Referenced by MoveUpTo.
bool Alignment::xDownDistanceArrived
Referenced by MoveDownTo.
bool Alignment::yDownDistanceArrived
Referenced by MoveDownTo.
bool Alignment::zDownDistanceArrived
Referenced by MoveDownTo.
bool Alignment::allDownDistanceArrived
Referenced by MoveDownTo.
bool Alignment::XAligned
Referenced by AlignLoop, calibratePrintHead.
bool Alignment::YAligned
Referenced by AlignLoop, calibratePrintHead.
bool Alignment::ZAligned
Referenced by AlignLoop, calibratePrintHead.
Alignment::Alignment(Nema8 *Motor_x, Nema8 *Motor_y, Nema8 *Motor_z, DistanceSensor *DistanceM_x, DistanceSensor *DistanceM_y, DistanceSensor *DistanceM_z, endSwitch *endSwitch_x, endSwitch *endSwitch_y, endSwitch *endSwitch_z)
References DistanceM_x, DistanceM_y, DistanceM_z, endSwitch_x, endSwitch_y, endSwitch_z, Motor_x, Motor_y, Motor_z.
Alignment::Alignment(Nema8 *Motor_x, Nema8 *Motor_y, Nema8 *Motor_z, DistanceSensor *DistanceM_x, DistanceSensor *DistanceM_y, DistanceSensor *DistanceM_z, endSwitch *endSwitch_x, endSwitch *endSwitch_y, endSwitch *endSwitch_z, endSwitch *endSwitch_stop, lightBarrier *lightBarrier_x, lightBarrier *lightBarrier_y, lightBarrier *lightBarrier_z)
References DistanceM_x, DistanceM_y, DistanceM_z, endSwitch_stop, endSwitch_x, endSwitch_y, endSwitch_z, lightBarrier_x, lightBarrier_y, lightBarrier_z, Motor_x, Motor_y, Motor_z.
Alignment::Alignment(Nema8 *Motor_x, Nema8 *Motor_y, Nema8 *Motor_z, Nema8 *Motor_PrintHead, DistanceSensor *DistanceM_x, DistanceSensor *DistanceM_y, DistanceSensor *DistanceM_z, endSwitch *endSwitch_x, endSwitch *endSwitch_y, endSwitch *endSwitch_z, endSwitch *endSwitch_stop, lightBarrier *lightBarrier_x, lightBarrier *lightBarrier_y, lightBarrier *lightBarrier_z)
References DistanceM_x, DistanceM_y, DistanceM_z, endSwitch_stop, endSwitch_x, endSwitch_y, endSwitch_z, lightBarrier_x, lightBarrier_y, lightBarrier_z, Motor_PrintHead, Motor_x, Motor_y, Motor_z.
retVal Alignment::MoveDistanceMSafe(Nema8 *Mref, int direction, float distance)
References Motor_x, Motor_y, Motor_z, MoveDistanceXloop, MoveDistanceYloop, MoveDistanceZloop.
Referenced by MoveMotorUpCmd::execute, MoveMotorDownCmd::execute, MoveMotorUpCmd::undo, MoveMotorDownCmd::undo.
retVal Alignment::MoveDistanceXloop(int direction, float distance)
References checkLimitUpX, isStopButtonPressed, Motor_x, MoveDistanceX, ok, a4988::StepCounter, yield.
Referenced by MoveDistanceMSafe.
retVal Alignment::MoveDistanceYloop(int direction, float distance)
References checkLimitUpY, isStopButtonPressed, Motor_y, MoveDistanceY, ok, a4988::StepCounter, yield.
Referenced by MoveDistanceMSafe.
retVal Alignment::MoveDistanceZloop(int direction, float distance)
References checkLimitUpZ, isStopButtonPressed, Motor_z, MoveDistanceZ, ok, a4988::StepCounter, yield.
Referenced by MoveDistanceMSafe.
retVal Alignment::RotateAnglePHloop(Nema8 *Mref, int direction, float angle)
References isStopButtonPressed, Motor_PrintHead, ok, rotateAnglePH, yield.
Referenced by RotateMotorClkCmd::execute, RotateMotorCclkCmd::execute, RotateMotorClkCmd::undo, RotateMotorCclkCmd::undo.
bool Alignment::isStopButtonPressed()
References endSwitch_stop, endSwitch::get_current_state.
Referenced by MoveDistanceXloop, MoveDistanceYloop, MoveDistanceZloop, RotateAnglePHloop.
void Alignment::initFirmwareUnit()
References DisableAll, initSensors, Motor_PrintHead, a4988::setDelay, STEP_DELAY_PRINTHEAD_MOTOR.
retVal Alignment::StepOnceX(int direction)
References Motor_x, ok, a4988::setDirection, a4988::stepOnce.
Referenced by calibratePrintHead, GoToReferenceUp, MoveAngleX, MoveDistanceX, StepDownXMax, StepUpXMax.
retVal Alignment::StepOnceY(int direction)
References Motor_y, ok, a4988::setDirection, a4988::stepOnce.
Referenced by calibratePrintHead, GoToReferenceUp, MoveAngleY, MoveDistanceY, StepDownYMax, StepUpYMax.
retVal Alignment::StepOnceZ(int direction)
References Motor_z, ok, a4988::setDirection, a4988::stepOnce.
Referenced by calibratePrintHead, GoToReferenceUp, MoveAngleZ, MoveDistanceZ, StepDownZMax, StepUpZMax.
retVal Alignment::MoveDistanceX(int direction, float distance)
References ConvertDistanceToStep, err, Motor_x, ok, a4988::StepCounter, StepOnceX, a4988::TotalStepCounted.
Referenced by GoToReferenceUp, MoveDistanceAll, MoveDistanceXloop, MoveDistanceXSafe.
retVal Alignment::MoveDistanceY(int direction, float distance)
References ConvertDistanceToStep, err, Motor_y, ok, a4988::StepCounter, StepOnceY, a4988::TotalStepCounted.
Referenced by GoToReferenceUp, MoveDistanceAll, MoveDistanceYloop, MoveDistanceYSafe.
retVal Alignment::MoveDistanceZ(int direction, float distance)
References ConvertDistanceToStep, err, Motor_z, ok, a4988::StepCounter, StepOnceZ, a4988::TotalStepCounted.
Referenced by GoToReferenceUp, MoveDistanceAll, MoveDistanceZloop, MoveDistanceZSafe.
retVal Alignment::MoveDistanceAll(int direction, float distance)
References err, MoveDistanceX, MoveDistanceY, MoveDistanceZ, ok.
Referenced by MoveDistanceAllSafe.
retVal Alignment::MoveAngleX(int direction, float angle)
References convertAngleToStep, err, Motor_x, ok, a4988::StepCounter, StepOnceX.
Referenced by MoveAngleAll, MoveAngleXSafe.
retVal Alignment::MoveAngleY(int direction, float angle)
References convertAngleToStep, err, Motor_y, ok, a4988::StepCounter, StepOnceY.
Referenced by MoveAngleAll, MoveAngleYSafe.
retVal Alignment::MoveAngleZ(int direction, float angle)
References convertAngleToStep, err, Motor_z, ok, a4988::StepCounter, StepOnceZ.
Referenced by MoveAngleAll, MoveAngleZSafe.
retVal Alignment::MoveAngleAll(int direction, float angle)
References err, MoveAngleX, MoveAngleY, MoveAngleZ, ok.
Referenced by MoveAngleAllSafe.
double Alignment::getValueSensorX()
References DistanceM_x, DistanceSensor::getCurrentDistance.
Referenced by getDistancePlatformToMlX.
double Alignment::getValueSensorY()
References DistanceM_y, DistanceSensor::getCurrentDistance.
Referenced by getDistancePlatformToMlY.
double Alignment::getValueSensorZ()
References DistanceM_z, DistanceSensor::getCurrentDistance.
Referenced by getDistancePlatformToMlZ.
bool Alignment::getReadingEndstopX()
References endSwitch_x, endSwitch::get_current_state.
Referenced by checkLimitDownX.
bool Alignment::getReadingEndstopY()
References endSwitch_y, endSwitch::get_current_state.
Referenced by checkLimitDownY.
bool Alignment::getReadingEndstopZ()
References endSwitch_z, endSwitch::get_current_state.
Referenced by checkLimitDownZ.
bool Alignment::getReadingLightBarrierX()
References lightBarrier::get_current_state, lightBarrier_x.
Referenced by checkLimitUpX.
bool Alignment::getReadingLightBarrierY()
References lightBarrier::get_current_state, lightBarrier_y.
Referenced by checkLimitUpY.
bool Alignment::getReadingLightBarrierZ()
References lightBarrier::get_current_state, lightBarrier_z.
Referenced by checkLimitUpZ.
retVal Alignment::GoToReferenceDown()
References MoveHomeAll.
int Alignment::convertDistanceToStepMicros(float distance)
References Linear_travel_per_step, MicroResolution.
int Alignment::convertAngleToStep(float angle)
References Angle_per_step.
Referenced by MoveAngleX, MoveAngleY, MoveAngleZ, rotateAnglePH.
float Alignment::getDistancePrintHeadToMl()
References DISTANCE_PRINTHEAD_PLATFORM, getDistancePlatformToMlXYZ.
float Alignment::getDistancePrintHeadToMlX()
References DISTANCE_PRINTHEAD_PLATFORM, getDistancePlatformToMlX.
Referenced by calibratePrintHead.
float Alignment::getDistancePrintHeadToMlY()
References DISTANCE_PRINTHEAD_PLATFORM, getDistancePlatformToMlY.
Referenced by calibratePrintHead.
float Alignment::getDistancePrintHeadToMlZ()
References DISTANCE_PRINTHEAD_PLATFORM, getDistancePlatformToMlZ.
Referenced by calibratePrintHead.
float Alignment::getDistancePlatformToMlX()
References getValueSensorX, MotorSensorHolderThickness.
Referenced by getDistancePlatformToMlXYZ, getDistancePrintHeadToMlX.
float Alignment::getDistancePlatformToMlY()
References getValueSensorY, MotorSensorHolderThickness.
Referenced by getDistancePlatformToMlXYZ, getDistancePrintHeadToMlY.
float Alignment::getDistancePlatformToMlZ()
References getValueSensorZ, MotorSensorHolderThickness.
Referenced by getDistancePlatformToMlXYZ, getDistancePrintHeadToMlZ.
float Alignment::getDistancePlatformToMlXYZ()
References getDistancePlatformToMlX, getDistancePlatformToMlY, getDistancePlatformToMlZ.
Referenced by getDistancePrintHeadToMl.
retVal Alignment::GoToReferenceUp()
References checkLimitUpX, checkLimitUpY, checkLimitUpZ, down, err, lightBarrier::IsTraversed, lightBarrier_x, lightBarrier_y, lightBarrier_z, Motor_x, Motor_y, Motor_z, MoveDistanceX, MoveDistanceY, MoveDistanceZ, ok, StepOnceX, StepOnceY, StepOnceZ, a4988::TotalStepCounted, up.
retVal Alignment::calibratePrintHead()
References checkLimitDownX, checkLimitDownY, checkLimitDownZ, checkLimitUpX, checkLimitUpY, checkLimitUpZ, DistanceM_x, DistanceM_y, DistanceM_z, down, err, DistanceSensor::getCurrentDistance, getDistancePrintHeadToMlX, getDistancePrintHeadToMlY, getDistancePrintHeadToMlZ, Keyence_rs232_interface::getValueOutputHeadAll, DistanceSensor::IkeyenceRS232, ok, SensorThreashold, StepOnceX, StepOnceY, StepOnceZ, TargetDistancePHToMl, up, XAligned, YAligned, ZAligned.
Referenced by CalibrateCmd::execute.
bool Alignment::checkLimitUpX()
References getReadingLightBarrierX, lightBarrier_x, lightBarrier::TraversedState.
Referenced by calibratePrintHead, checkLimitUpXYZ, GoToReferenceUp, MoveAngleXSafe, MoveDistanceXloop, MoveDistanceXSafe, StepUpXMax.
bool Alignment::checkLimitUpY()
References getReadingLightBarrierY, lightBarrier_y, lightBarrier::TraversedState.
Referenced by calibratePrintHead, checkLimitUpXYZ, GoToReferenceUp, MoveAngleYSafe, MoveDistanceYloop, MoveDistanceYSafe, StepUpYMax.
bool Alignment::checkLimitUpZ()
References getReadingLightBarrierZ, lightBarrier_y, lightBarrier::TraversedState.
Referenced by calibratePrintHead, checkLimitUpXYZ, GoToReferenceUp, MoveAngleZSafe, MoveDistanceZloop, MoveDistanceZSafe, StepUpZMax.
bool Alignment::checkLimitUpXYZ()
References checkLimitUpX, checkLimitUpY, checkLimitUpZ.
Referenced by MoveAngleAllSafe, MoveDistanceAllSafe.
bool Alignment::checkLimitDownX()
References endSwitch_x, getReadingEndstopX, endSwitch::PressedState.
Referenced by calibratePrintHead, checkLimitDownXYZ, MoveAngleXSafe, MoveDistanceXSafe, StepDownXMax.
bool Alignment::checkLimitDownY()
References endSwitch_y, getReadingEndstopY, endSwitch::PressedState.
Referenced by calibratePrintHead, checkLimitDownXYZ, MoveAngleYSafe, MoveDistanceYSafe, StepDownYMax.
bool Alignment::checkLimitDownZ()
References endSwitch_z, getReadingEndstopZ, endSwitch::PressedState.
Referenced by calibratePrintHead, checkLimitDownXYZ, MoveAngleZSafe, MoveDistanceZSafe, StepDownZMax.
bool Alignment::checkLimitDownXYZ()
References checkLimitDownX, checkLimitDownY, checkLimitDownZ.
Referenced by MoveAngleAllSafe, MoveDistanceAllSafe.
retVal Alignment::StepDownXMax()
References checkLimitDownX, down, err, ok, StepOnceX.
retVal Alignment::StepDownYMax()
References checkLimitDownY, down, err, ok, StepOnceY.
retVal Alignment::StepDownZMax()
References checkLimitDownZ, down, err, ok, StepOnceZ.
retVal Alignment::StepUpXMax()
References checkLimitUpX, err, ok, StepOnceX, up.
retVal Alignment::StepUpYMax()
References checkLimitUpY, err, ok, StepOnceY, up.
retVal Alignment::StepUpZMax()
References checkLimitUpZ, err, ok, StepOnceZ, up.
retVal Alignment::MoveDistanceXSafe(int direction, float distance)
References checkLimitDownX, checkLimitUpX, down, Motor_x, MoveDistanceX, ok, a4988::StepCounter, up.
Referenced by oscillateSys.
retVal Alignment::MoveDistanceYSafe(int direction, float distance)
References checkLimitDownY, checkLimitUpY, down, Motor_y, MoveDistanceY, ok, a4988::StepCounter, up.
Referenced by oscillateSys.
retVal Alignment::MoveDistanceZSafe(int direction, float distance)
References checkLimitDownZ, checkLimitUpZ, down, Motor_z, MoveDistanceZ, ok, a4988::StepCounter, up.
Referenced by oscillateSys.
retVal Alignment::MoveDistanceAllSafe(int direction, float distance)
References checkLimitDownXYZ, checkLimitUpXYZ, down, Motor_x, Motor_y, Motor_z, MoveDistanceAll, ok, a4988::StepCounter, up.
retVal Alignment::MoveAngleXSafe(int direction, float Angle)
References checkLimitDownX, checkLimitUpX, down, Motor_x, MoveAngleX, ok, a4988::StepCounter, up.
retVal Alignment::MoveAngleYSafe(int direction, float Angle)
References checkLimitDownY, checkLimitUpY, down, Motor_y, MoveAngleY, ok, a4988::StepCounter, up.
retVal Alignment::MoveAngleZSafe(int direction, float Angle)
References checkLimitDownZ, checkLimitUpZ, down, Motor_z, MoveAngleZ, ok, a4988::StepCounter, up.
retVal Alignment::MoveAngleAllSafe(int direction, float Angle)
References checkLimitDownXYZ, checkLimitUpXYZ, down, Motor_x, Motor_y, Motor_z, MoveAngleAll, ok, a4988::StepCounter, up.
retVal Alignment::StepOncePH(int direction)
References Motor_PrintHead, ok, a4988::setDirection, a4988::stepOnce.
Referenced by oscillateSys, rotateAnglePH.
retVal Alignment::rotateFullRevPH(int direction)
References rotateAnglePH.
retVal Alignment::rotateAnglePH(int direction, float Angle)
References convertAngleToStep, err, Motor_PrintHead, ok, a4988::StepCounter, StepOncePH, a4988::TotalStepCounted.
Referenced by movePhToRefX, RotateAnglePHloop, rotateFullRevPH.
retVal Alignment::oscillateSys(float desired_angle, int num_revolutions, bool default_sens=clk, bool reverse_sense=true)
References Angle_per_step, down, MoveDistanceXSafe, MoveDistanceYSafe, MoveDistanceZSafe, StepOncePH, up.
retVal Alignment::movePhToRefX()
References a4988::direction, DistanceM_x, DistanceSensor::getCurrentDistance, Keyence_rs232_interface::getValueOutputHeadAll, DistanceSensor::IkeyenceRS232, Motor_PrintHead, rotateAnglePH.
retVal Alignment::initSensors()
Referenced by initFirmwareUnit.
void Alignment::incrementTotalStepCounted()
References Motor_PrintHead, Motor_x, Motor_y, Motor_z, a4988::StepCounter, a4988::TotalStepCounted.
void Alignment::resetStepCounter()
References Motor_PrintHead, Motor_x, Motor_y, Motor_z, a4988::StepCounter.
float Alignment::getCurrentPosX()
References DistanceM_x, EndeffectorThickness, DistanceSensor::getCurrentDistance, MotorSensorHolderThickness, RodLength.
Referenced by CheckBoundaryX.
float Alignment::getCurrentPosY()
References DistanceM_y, EndeffectorThickness, DistanceSensor::getCurrentDistance, MotorSensorHolderThickness, RodLength.
float Alignment::getCurrentPosZ()
References DistanceM_z, EndeffectorThickness, DistanceSensor::getCurrentDistance, MotorSensorHolderThickness, RodLength.
float Alignment::CheckBoundaryX(float targetDistance, int direction)
References AllowedPath, ConvertDistanceToStep, down, getCurrentPosX, Motor_x, a4988::step, up.
retVal Alignment::InitAlign(bool enable=on)
setup stuff to initialise enable, direction and so on
retVal
References a4988::enable, Motor_PrintHead, Motor_x, Motor_y, Motor_z, ok.
retVal Alignment::EnableAll(bool enable=on)
References a4988::enable, Motor_PrintHead, Motor_x, Motor_y, Motor_z, ok.
retVal Alignment::DisableAll(bool enable=off)
References a4988::enable, Motor_PrintHead, Motor_x, Motor_y, Motor_z, ok.
Referenced by initFirmwareUnit.
retVal Alignment::MoveHomeAll()
Move all motors home @algorithm: check if every motor endswitch is not pressed, then move Nema8 up.
retVal
References down, endSwitch_x, endSwitch_y, endSwitch_z, err, endSwitch::get_current_state, endSwitch::Ispressed, Motor_x, Motor_y, Motor_z, ok, endSwitch::PressedState, a4988::setDirection, a4988::stepOnce, a4988::TotalStepCounted, up.
Referenced by GoToReferenceDown.
retVal Alignment::AlignLoop()
This is the main function to keep track of alignment during process @algorithm: compare value of distance sensor for each motor with target and calibrate.
retVal
References DistanceM_x, DistanceM_y, DistanceM_z, down, err, DistanceSensor::getCurrentDistance, Keyence_rs232_interface::getValueOutputHeadAll, DistanceSensor::IkeyenceRS232, Motor_x, Motor_y, Motor_z, ok, SensorThreashold, a4988::setDirection, a4988::stepOnce, TargetDistanceSensorToMl, up, XAligned, YAligned, ZAligned.
float Alignment::getRemainingDistanceX()
References DistanceM_x, EndeffectorThickness, DistanceSensor::getCurrentDistance, RodLength, SensorThickness.
float Alignment::getRemainingDistanceY()
References DistanceM_y, EndeffectorThickness, DistanceSensor::getCurrentDistance, RodLength, SensorThickness.
float Alignment::getRemainingDistanceZ()
get the real distance based on mechanical construction in this setup
float
References DistanceM_z, EndeffectorThickness, DistanceSensor::getCurrentDistance, RodLength, SensorThickness.
float Alignment::getMinX()
get mesured values minus thickness of sensor: equal to 0 position
float
References DistanceM_x, DistanceSensor::getCurrentDistance, SensorThickness.
Referenced by getMaxX, MoveDown, MoveDownTo.
float Alignment::getMinY()
References DistanceM_y, DistanceSensor::getCurrentDistance, SensorThickness.
Referenced by getMaxY, MoveDown, MoveDownTo.
float Alignment::getMinZ()
References DistanceM_z, DistanceSensor::getCurrentDistance, SensorThickness.
Referenced by getMaxZ, MoveDown, MoveDownTo.
float Alignment::getMaxX()
References getMinX, LeadScrewLEngth, MotorLength, MotorSensorHolderThickness.
Referenced by MoveUp, MoveUpTo.
float Alignment::getMaxY()
References getMinY, LeadScrewLEngth, MotorLength, MotorSensorHolderThickness.
Referenced by MoveUp, MoveUpTo.
float Alignment::getMaxZ()
References getMinZ, LeadScrewLEngth, MotorLength, MotorSensorHolderThickness.
Referenced by MoveUp, MoveUpTo.
retVal Alignment::MoveUp(bool x, bool y, bool z, bool checkLimit)
References allUpMax, getMaxX, getMaxY, getMaxZ, LeadScrewLEngth, Motor_x, Motor_y, Motor_z, ok, RodLength_EndeffectorThickness, SensorThreashold, a4988::setDirection, a4988::stepOnce, up, xUpMax, yUpMax, zUpMax.
retVal Alignment::MoveDown(bool x, bool y, bool z, bool checkLimit)
References allDownMax, down, getMinX, getMinY, getMinZ, Motor_x, Motor_y, Motor_z, ok, RodLength_EndeffectorThickness, SensorThreashold, a4988::setDirection, a4988::stepOnce, xDownMax, yDownMax, zDownMax.
retVal Alignment::MoveUpTo(bool x, bool y, bool z, bool checkLimit, float distance)
References allUpDistanceArrived, ConvertDistanceToStep, getMaxX, getMaxY, getMaxZ, LeadScrewLEngth, Motor_x, Motor_y, Motor_z, ok, RodLength_EndeffectorThickness, SensorThreashold, a4988::setDirection, a4988::step, a4988::stepOnce, up, xUpDistanceArrived, yUpDistanceArrived, zUpDistanceArrived.
retVal Alignment::MoveDownTo(bool x, bool y, bool z, bool checkLimit, float distance)
References allDownDistanceArrived, ConvertDistanceToStep, down, getMinX, getMinY, getMinZ, Motor_x, Motor_y, Motor_z, ok, RodLength_EndeffectorThickness, SensorThreashold, a4988::setDirection, a4988::step, a4988::stepOnce, xDownDistanceArrived, yDownDistanceArrived, zDownDistanceArrived.
retVal Alignment::setTargetDistancePHToML(float distance)
set new target distance to ML
distance retVal
References ok, TargetDistancePHToMl.
Referenced by CalibrateCmd::execute.
retVal Alignment::setTargetDistanceSensorToML(float distance)
References ok, TargetDistanceSensorToMl.
int Alignment::ConvertDistanceToStep(float distance)
convert distance in mm or m to step or microstep
distance int
References Linear_travel_per_step.
Referenced by CheckBoundaryX, MoveDistanceX, MoveDistanceY, MoveDistanceZ, MoveDownTo, MoveUpTo.