UUID_MANAGER
String* UUID_MANAGER::ObjUUID
String UUID_MANAGER::default_id
String UUID_MANAGER::temp_id
String UUID_MANAGER::sf6_id
String UUID_MANAGER::align_id
String UUID_MANAGER::print_id
String UUID_MANAGER::cnt_id
String UUID_MANAGER::delta_id
UUID_MANAGER::UUID_MANAGER(String WhichId)
Construct a new uuid manager object example: pass "align" to constructor to automaticly to align id.
WhichId
References _checkIfUUIDisWritten.
String UUID_MANAGER::get_UUID_EEPROM()
wrapper function to get internal stored id
String
Referenced by getUUID::execute, setUUID::execute.
void UUID_MANAGER::set_UUID_EEPROM(const String new_uuid)
wrapper function to set new internal id
Referenced by setUUID::execute, setUUID::undo.
void UUID_MANAGER::_checkIfUUIDisWritten()
write id at boot, don't overwrite if exists
private method write to eeprom to get the idea true false
Referenced by UUID_MANAGER.
void UUID_MANAGER::_writeStringToEEPROM(int addrOffset, const String &strToWrite)
write string to eeprom
addrOffset strToWrite int
String UUID_MANAGER::_readStringFromEEPROM(int addrOffset)
read string from eeprom
addrOffset strToRead int
String UUID_MANAGER::_get_default_id()
Get the default id object.
String
String UUID_MANAGER::_get_temp_id()
Get the temp id object.
String
String UUID_MANAGER::_get_align_id()
Get the wafer alignement id object.
String
String UUID_MANAGER::_get_sf6_id()
Get the sf6 id object.
String
String UUID_MANAGER::_get_delta_id()
String UUID_MANAGER::_get_cnt_id()
String UUID_MANAGER::_get_print_id()
void UUID_MANAGER::_set_default_id(String new_id)
Get the default id object.
String
void UUID_MANAGER::_set_temp_id(String new_id)
set the temp id object
void UUID_MANAGER::_set_align_id(String new_id)
set the wafer alignement id object
void UUID_MANAGER::_set_sf6_id(String new_id)
set the sf6 id object
void UUID_MANAGER::_set_delta_id(String new_id)
void UUID_MANAGER::_set_cnt_id(String new_id)
void UUID_MANAGER::_set_print_id(String new_id)