Keyence_rs232_interface
HardwareSerial* Keyence_rs232_interface::serialHandler
Referenced by getValueMultipleOutputHead, getValueOutputHeadAll, getValueSingleOutputHead, initKeyenceCom, Keyence_rs232_interface, setCommunicationMode, setGeneralMode, setSerialHandler.
unsigned long Keyence_rs232_interface::baudrate
Referenced by initKeyenceCom, Keyence_rs232_interface, setSerialBaudrate.
Keyence_rs232_interface::Keyence_rs232_interface(HardwareSerial &serHandler, unsigned long baud)
References baudrate, serialHandler.
void Keyence_rs232_interface::setSerialHandler(HardwareSerial &serHandler)
References serialHandler.
void Keyence_rs232_interface::setSerialBaudrate(unsigned long baud)
References baudrate.
void Keyence_rs232_interface::initKeyenceCom()
References baudrate, serialHandler.
double Keyence_rs232_interface::getValueSingleOutputHead(int output_head_Nr) override
References Keyence_base::commands, CR, Keyence_base::findCommand, serialHandler.
double * Keyence_rs232_interface::getValueMultipleOutputHead(String HeadsArray) override
References Keyence_base::commands, Keyence_base::findCommand, Keyence_base::HeadsArray, serialHandler.
double * Keyence_rs232_interface::getValueOutputHeadAll() override
References CR, Keyence_base::HeadsCount, Keyence_base::LookUpValues, serialHandler.
Referenced by Alignment::AlignLoop, Alignment::calibratePrintHead, DistanceSensor::getCurrentDistance, Alignment::movePhToRefX.
void Keyence_rs232_interface::setGeneralMode() override
References Keyence_base::commands, CR, Keyence_base::findCommand, serialHandler.
void Keyence_rs232_interface::setCommunicationMode() override
References Keyence_base::commands, CR, Keyence_base::findCommand, serialHandler.