DistanceSensor
int DistanceSensor::Pin
bool DistanceSensor::state
double DistanceSensor::currentDistance
Referenced by getCurrentDistance.
Keyence_rs232_interface* DistanceSensor::IkeyenceRS232
Referenced by Alignment::AlignLoop, Alignment::calibratePrintHead, getCurrentDistance, Alignment::movePhToRefX.
int DistanceSensor::HeadNum
Referenced by getCurrentDistance, printDistance.
Keyence_base* DistanceSensor::Kbase
DistanceSensor::DistanceSensor(int OutputHeadNumber)
void DistanceSensor::setKeyenceCom()
double DistanceSensor::getCurrentDistance()
References currentDistance, Keyence_rs232_interface::getValueOutputHeadAll, HeadNum, IkeyenceRS232, Keyence_base::LookUpValues.
Referenced by Alignment::AlignLoop, Alignment::calibratePrintHead, getSensorValueCmd::execute, Alignment::getCurrentPosX, Alignment::getCurrentPosY, Alignment::getCurrentPosZ, Alignment::getMinX, Alignment::getMinY, Alignment::getMinZ, Alignment::getRemainingDistanceX, Alignment::getRemainingDistanceY, Alignment::getRemainingDistanceZ, Alignment::getValueSensorX, Alignment::getValueSensorY, Alignment::getValueSensorZ, Alignment::movePhToRefX.
void DistanceSensor::printDistance(float val)
References HeadNum.