a4988
int a4988::direction
Referenced by a4988, getDirection, Alignment::movePhToRefX, Nema8::Nema8, reverseDirection, setDirection, stepOnce.
int a4988::motor_steps
Referenced by a4988, getSpeed, Nema8::Nema8.
unsigned long a4988::step_delay
Referenced by a4988, getDelay, getSpeed, Nema8::Nema8, setDelay, stepOnce.
int a4988::num_steps
Referenced by step.
int a4988::step_number
int a4988::step_mode
Referenced by setStepMode.
int a4988::step_pin
Referenced by a4988, Nema8::Nema8, stepOnce.
int a4988::ms1_pin
Referenced by a4988, Nema8::Nema8, setStepMode.
int a4988::ms2_pin
Referenced by a4988, Nema8::Nema8, setStepMode.
int a4988::ms3_pin
Referenced by a4988, Nema8::Nema8, setStepMode.
int a4988::dir_pin
Referenced by a4988, Nema8::Nema8, setDirection.
int a4988::enable_pin
Referenced by a4988, enable, Nema8::Nema8.
int a4988::StepCounter
Referenced by Alignment::incrementTotalStepCounted, Alignment::MoveAngleAllSafe, Alignment::MoveAngleX, Alignment::MoveAngleXSafe, Alignment::MoveAngleY, Alignment::MoveAngleYSafe, Alignment::MoveAngleZ, Alignment::MoveAngleZSafe, Alignment::MoveDistanceAllSafe, Alignment::MoveDistanceX, Alignment::MoveDistanceXloop, Alignment::MoveDistanceXSafe, Alignment::MoveDistanceY, Alignment::MoveDistanceYloop, Alignment::MoveDistanceYSafe, Alignment::MoveDistanceZ, Alignment::MoveDistanceZloop, Alignment::MoveDistanceZSafe, Alignment::resetStepCounter, Alignment::rotateAnglePH.
int a4988::TotalStepCounted
Referenced by getStepCounter, Alignment::GoToReferenceUp, Alignment::incrementTotalStepCounted, Alignment::MoveDistanceX, Alignment::MoveDistanceY, Alignment::MoveDistanceZ, Alignment::MoveHomeAll, Alignment::rotateAnglePH, stepOnce.
a4988::a4988(int motor_steps, int ms1_pin, int ms2_pin, int ms3_pin, int dir_pin, int enable_pin, int step_pin, bool direction)
References dir_pin, direction, enable_pin, motor_steps, ms1_pin, ms2_pin, ms3_pin, STEP_DELAY, step_delay, step_pin.
void a4988::enable(int enable)
References enable_pin.
Referenced by Alignment::DisableAll, Alignment::EnableAll, EnableMotorCmd::execute, Alignment::InitAlign, EnableMotorCmd::undo.
void a4988::step(unsigned long num_steps)
References num_steps, stepOnce.
Referenced by Alignment::CheckBoundaryX, Alignment::MoveDownTo, Alignment::MoveUpTo.
void a4988::stepOnce(void)
References cclk, clk, direction, down, step_delay, step_pin, TotalStepCounted, up.
Referenced by Alignment::AlignLoop, Alignment::MoveDown, Alignment::MoveDownTo, Alignment::MoveHomeAll, Alignment::MoveUp, Alignment::MoveUpTo, step, Alignment::StepOncePH, Alignment::StepOnceX, Alignment::StepOnceY, Alignment::StepOnceZ.
void a4988::stepMotor(int this_step)
void a4988::reverseDirection()
References direction, down, setDirection, up.
float a4988::getSpeed()
References motor_steps, step_delay.
Referenced by getMotorSpeedCmd::execute, setMotorSpeedCmd::execute.
float a4988::getDelay()
References step_delay.
Referenced by getMotorDelayCmd::execute, setMotorDelayCmd::execute.
int a4988::getStepCounter()
References TotalStepCounted.
bool a4988::getDirection()
References direction.
Referenced by getMotorDirectionCmd::execute, setMotorDirectionCmd::execute.
void a4988::setDelay(unsigned long delay)
References step_delay.
Referenced by setMotorDelayCmd::execute, Alignment::initFirmwareUnit, setMotorDelayCmd::undo.
void a4988::setSpeed(int speed)
Referenced by setMotorSpeedCmd::execute, setMotorSpeedCmd::undo.
void a4988::setDirection(int direction)
References dir_pin, direction, down.
Referenced by Alignment::AlignLoop, setMotorDirectionCmd::execute, Alignment::MoveDown, Alignment::MoveDownTo, Alignment::MoveHomeAll, Alignment::MoveUp, Alignment::MoveUpTo, reverseDirection, Alignment::StepOncePH, Alignment::StepOnceX, Alignment::StepOnceY, Alignment::StepOnceZ, setMotorDirectionCmd::undo.
void a4988::setStepMode(int stepMode)
References ms1_pin, ms2_pin, ms3_pin, step_mode.