CmdBufferObject
uint8_t CmdBufferObject::m_endChar
Character for handling the end of serial data communication
uint8_t CmdBufferObject::m_bsChar
size_t CmdBufferObject::m_dataOffset
bool CmdBufferObject::m_echo
CmdBufferObject::CmdBufferObject()
Clear buffer and set defaults.
bool CmdBufferObject::readFromSerial(Stream *serial, uint32_t timeOut=0)
Read data from serial communication to buffer. It read only printable ASCII character from serial. All other will ignore for buffer. serial Arduino Serial object from read commands timeOut Set a time out in millisec or 0 for none TRUE if data readed until end character or FALSE is a timeout receive or buffer is full.
References readSerialChar.
Referenced by CmdCallbackObject::loopCmdProcessing.
bool CmdBufferObject::readSerialChar(Stream *serial)
Read one char from serial communication to buffer if available. It read only printable ASCII character from serial. All other will ignore for buffer. This function only ready currently available data and doesn't wait for a full command (= end character) serial Arduino Serial object from read commands TRUE if data readed until end character or FALSE if not.
References CMDBUFFER_CHAR_PRINTABLE, getBuffer, getBufferSize.
Referenced by readFromSerial, CmdCallbackObject::updateCmdProcessing.
void CmdBufferObject::setEndChar(uint8_t end)
Set a ASCII character for serial cmd end. Default value is LF. Macros for helping are: CMDBUFFER_CHAR_LF CMDBUFFER_CHAR_CR end ASCII character
void CmdBufferObject::setBackChar(uint8_t backspace)
Set a ASCII character for serial cmd backspace. Default value is BS. Macros for helping are: CMDBUFFER_CHAR_BS CMDBUFFER_CHAR_DEL backspace ASCII character
void CmdBufferObject::setEcho(bool echo)
Set echo serial on (true) or off (false) echo bool
char * CmdBufferObject::getStringFromBuffer()
Cast Buffer to c string. Buffer as cstring
References getBuffer.
virtual void CmdBufferObject::clear()=0
Clear buffer with 0x00
Referenced by CmdCallbackObject::loopCmdProcessing, CmdCallbackObject::updateCmdProcessing.
virtual uint8_t * CmdBufferObject::getBuffer()=0
Return a null-terminated ('\0') string String from Buffer
Referenced by getStringFromBuffer, CmdParser::parseCmd, readSerialChar.
virtual size_t CmdBufferObject::getBufferSize()=0
Get size of buffer Size of buffer
Referenced by CmdParser::parseCmd, readSerialChar.