lightBarrier
bool lightBarrier::current_state
bool lightBarrier::last_state
bool lightBarrier::IsTraversed
Referenced by Alignment::GoToReferenceUp.
int lightBarrier::Pin
Referenced by get_current_state, lightBarrier.
bool lightBarrier::TraversedState
Referenced by Alignment::checkLimitUpX, Alignment::checkLimitUpY, Alignment::checkLimitUpZ, lightBarrier.
lightBarrier::lightBarrier()
lightBarrier::lightBarrier(int Pin, bool TraversedState)
Construct a new lightBarrier::lightBarrier object.
Pin
References Pin, TraversedState.
bool lightBarrier::get_current_state()
get current state
true false
References Pin.
Referenced by Alignment::getReadingLightBarrierX, Alignment::getReadingLightBarrierY, Alignment::getReadingLightBarrierZ.