Keyence_base
String Keyence_base::RawCommands[9][9]
std::map<String, String> Keyence_base::commands
Referenced by Keyence_rs232_interface::getValueMultipleOutputHead, Keyence_rs232_interface::getValueSingleOutputHead, Keyence_rs232_interface::setCommunicationMode, Keyence_rs232_interface::setGeneralMode.
std::vector< int > Keyence_base::NumUsedHeads
Referenced by listHeads.
int Keyence_base::HeadsCount
Referenced by Keyence_rs232_interface::getValueOutputHeadAll, listHeads.
int Keyence_base::HeadsArray[12]
Referenced by Keyence_rs232_interface::getValueMultipleOutputHead, listHeads.
double * Keyence_base::LookUpValues
Referenced by DistanceSensor::getCurrentDistance, Keyence_rs232_interface::getValueOutputHeadAll.
String Keyence_base::findCommand(String &command, std::map< String, String > &CommandMap)
Referenced by Keyence_rs232_interface::getValueMultipleOutputHead, Keyence_rs232_interface::getValueSingleOutputHead, Keyence_rs232_interface::setCommunicationMode, Keyence_rs232_interface::setGeneralMode.
virtual double Keyence_base::getValueSingleOutputHead(int output_head_Nr)=0
virtual double * Keyence_base::getValueMultipleOutputHead(String HeadsArray)=0
virtual double * Keyence_base::getValueOutputHeadAll()=0
virtual void Keyence_base::setGeneralMode()=0
virtual void Keyence_base::setCommunicationMode()=0
void Keyence_base::listHeads()
References HeadsArray, HeadsCount, NumUsedHeads, transformArrayToVector.
static void Keyence_base::printVectorElements(std::vector< T > &vec)
static void Keyence_base::printArrayElements(A &array)
static void Keyence_base::transformArrayToVector(A &array, std::vector< V > &vector)
Referenced by listHeads.