CmdParser
bool CmdParser::m_ignoreQuote
Parser obtion setOptIgnoreQuote
bool CmdParser::m_useKeyValue
Parser option setOptKeyValue
char CmdParser::m_seperator
Parser option setOptSeperator
uint8_t* CmdParser::m_buffer
Pointer to cmd buffer
size_t CmdParser::m_bufferSize
Size of cmd buffer
uint16_t CmdParser::m_paramCount
Number of parsed params
CmdParser::CmdParser()
Set member to default values.
uint16_t CmdParser::parseCmd(uint8_t *buffer, size_t bufferSize)
Parse a buffer with commands. This function change the buffer and only this object can handle the new buffer! buffer Buffer with cmd string bufferSize Size of buffer Number of params or CMDPARSER_ERROR
References CMDPARSER_CHAR_DQ, CMDPARSER_CHAR_EQ, CMDPARSER_ERROR.
Referenced by CmdCallbackObject::loopCmdProcessing, parseCmd, CmdCallbackObject::updateCmdProcessing.
uint16_t CmdParser::parseCmd(CmdBufferObject *cmdBuffer)
References CmdBufferObject::getBuffer, CmdBufferObject::getBufferSize, parseCmd.
uint16_t CmdParser::parseCmd(char *cmdStr)
References parseCmd.
char * CmdParser::getCommand()
Get the initial command line word. String with cmd word or NULL if not exists
References getCmdParam.
Referenced by CmdCallbackObject::processCmd, CmdCallbackObject::processCmdVoid.
char * CmdParser::getCmdParam(uint16_t idx)
Get the param IDX from command line. idx Number of param to get String with param or NULL if not exists
Referenced by calibrate_cmd, equalCmdParam, getCommand, move_cmd, rotate_cmd, set_cmd.
uint16_t CmdParser::getParamCount()
Return the counter of parameter from cmd. Return the param counter of command
char * CmdParser::getValueFromKey(CmdParserString key)
If KeyValue option is set, search the value from a key pair. KEY=Value i.e. KEY is upper case setOptCmdUpper. key Key for search in cmd String with value or NULL if not exists
References getValueFromKey.
Referenced by equalValueFromKey, getValueFromKey.
bool CmdParser::equalCmdParam(uint16_t idx, CmdParserString value)
Check if param equal with value case sensitive. idx Number of param to get value String to compare TRUE if equal
References getCmdParam.
Referenced by calibrate_cmd, cmdParamExists, equalCommand, get_cmd, get_help, move_cmd, rotate_cmd, set_cmd.
bool CmdParser::equalCommand(CmdParserString value)
Check if command equal with value case sensitive. value String to compare TRUE if equal
References equalCmdParam.
bool CmdParser::equalValueFromKey(CmdParserString key, CmdParserString value)
Check if value equal from key case sensitive. key Key store in SRAM for search in cmd value String to compare in PROGMEM TRUE if equal
References getValueFromKey.
bool CmdParser::cmdParamExists(CmdParserString value)
Checks if a parameter/flag exists among all other passed command parameters. value String to look for among the parameters TRUE if found
References equalCmdParam.
void CmdParser::setOptIgnoreQuote(bool onOff=true)
Set parser option to ignore " quote for string. Default is off onOff Set option TRUE (on) or FALSE (off)
void CmdParser::setOptKeyValue(bool onOff=false)
Set parser option for handling KEY=Value parameter. Default is off onOff Set option TRUE (on) or FALSE (off)
void CmdParser::setOptSeperator(char seperator)
Set parser option for cmd seperator. Default is ' ' or CMDPARSER_CHAR_SP seperator Set character for seperator cmd
char * CmdParser::getValueFromKey(const char *key, bool progmem)
Handle internal key value search function. progmem TRUE key is store in progmem String with value or NULL if not exists