ICommand
virtual ICommand::~ICommand()
virtual void ICommand::execute()=0
Referenced by FirmInvoker::calibrate, Invoker::finish, get_cmd, MotorInvoker::getDelay, MotorInvoker::getDirection, MotorInvoker::getSpeed, move_cmd, MotorInvoker::moveDown, MotorInvoker::moveUp, reset_cmd, rotate_cmd, MotorInvoker::rotateCclk, MotorInvoker::rotateClk, set_cmd, MotorInvoker::setDelay, MotorInvoker::setDirection, MotorInvoker::setSpeed, sleep_cmd, Invoker::start.
virtual void ICommand::undo()=0
Referenced by MotorInvoker::moveDown, MotorInvoker::moveUp, MotorInvoker::rotateCclk, MotorInvoker::rotateClk.