.TH "_CmdCallback< STORESIZE, T >" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CmdCallback< STORESIZE, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdCallback\&.hpp>\fP
.PP
Inherits \fBCmdCallbackObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_CmdCallback\fP ()"
.br
.ti -1c
.RI "bool \fBaddCmd\fP (T cmdStr, \fBCmdCallFunct\fP cbFunct)"
.br
.ti -1c
.RI "virtual size_t \fBgetStoreSize\fP ()"
.br
.ti -1c
.RI "virtual bool \fBcheckStorePos\fP (size_t idx)"
.br
.ti -1c
.RI "virtual bool \fBcallStoreFunct\fP (size_t idx, \fBCmdParser\fP *cmdParser)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T \fBm_cmdList\fP [STORESIZE]"
.br
.ti -1c
.RI "\fBCmdCallFunct\fP \fBm_functList\fP [STORESIZE]"
.br
.ti -1c
.RI "size_t \fBm_nextElement\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<size_t STORESIZE, typename T>
.br
class _CmdCallback< STORESIZE, T >"
.PP
Definition at line \fB126\fP of file \fBCmdCallback\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<size_t STORESIZE, typename T > \fB_CmdCallback\fP< STORESIZE, T >\fB::_CmdCallback\fP ()\fC [inline]\fP"
Cleanup member data 
.PP
Definition at line \fB132\fP of file \fBCmdCallback\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<size_t STORESIZE, typename T > bool \fB_CmdCallback\fP< STORESIZE, T >::addCmd (T cmdStr, \fBCmdCallFunct\fP cbFunct)\fC [inline]\fP"
Link a callback function to command\&.
.PP
\fBParameters\fP
.RS 4
\fIcmdStr\fP A cmd string in progmem 
.br
\fIcbFunct\fP A callback function to process your things 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if you have space in buffer of object 
.RE
.PP

.PP
Definition at line \fB145\fP of file \fBCmdCallback\&.hpp\fP\&.
.SS "template<size_t STORESIZE, typename T > virtual bool \fB_CmdCallback\fP< STORESIZE, T >::callStoreFunct (size_t idx, \fBCmdParser\fP * cmdParser)\fC [inline]\fP, \fC [virtual]\fP"
@implement \fBCmdCallbackObject\fP 
.PP
Implements \fBCmdCallbackObject\fP\&.
.PP
Definition at line \fB180\fP of file \fBCmdCallback\&.hpp\fP\&.
.SS "template<size_t STORESIZE, typename T > virtual bool \fB_CmdCallback\fP< STORESIZE, T >::checkStorePos (size_t idx)\fC [inline]\fP, \fC [virtual]\fP"
@implement \fBCmdCallbackObject\fP 
.PP
Implements \fBCmdCallbackObject\fP\&.
.PP
Definition at line \fB168\fP of file \fBCmdCallback\&.hpp\fP\&.
.SS "template<size_t STORESIZE, typename T > virtual size_t \fB_CmdCallback\fP< STORESIZE, T >::getStoreSize ()\fC [inline]\fP, \fC [virtual]\fP"
@implement \fBCmdCallbackObject\fP 
.PP
Implements \fBCmdCallbackObject\fP\&.
.PP
Definition at line \fB163\fP of file \fBCmdCallback\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<size_t STORESIZE, typename T > T \fB_CmdCallback\fP< STORESIZE, T >::m_cmdList[STORESIZE]\fC [protected]\fP"
Array with list of commands 
.PP
Definition at line \fB193\fP of file \fBCmdCallback\&.hpp\fP\&.
.SS "template<size_t STORESIZE, typename T > \fBCmdCallFunct\fP \fB_CmdCallback\fP< STORESIZE, T >::m_functList[STORESIZE]\fC [protected]\fP"
List of function 
.br
 
.PP
Definition at line \fB196\fP of file \fBCmdCallback\&.hpp\fP\&.
.SS "template<size_t STORESIZE, typename T > size_t \fB_CmdCallback\fP< STORESIZE, T >::m_nextElement\fC [protected]\fP"
Pointer to next element in array 
.PP
\fBSee also\fP
.RS 4
\fBaddCmd\fP 
.RE
.PP

.PP
Definition at line \fB199\fP of file \fBCmdCallback\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
