.TH "C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include Directory Reference" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAlignment\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCmdBuffer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCmdCallback\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCmdParser\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCmdPatternCallbacks\&.h\fP"
.br
.RI "binding command inokation with parser callbacks "
.ti -1c
.RI "file \fBCmdPatternClasses\&.h\fP"
.br
.RI "interface Command &\fBInvoker\fP and Classes Definition here "
.ti -1c
.RI "file \fBComHandler\&.hpp\fP"
.br
.RI "This Class handles serial communication layer\&. "
.ti -1c
.RI "file \fBConfigs\&.h\fP"
.br
.RI "Place the definition of Macros here like pins, enumerate and so on\&. "
.ti -1c
.RI "file \fBDistanceSensor\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDriverA4988\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEndSwitch\&.hpp\fP"
.br
.RI "endswitch class "
.ti -1c
.RI "file \fBGlobals\&.h\fP"
.br
.RI "include declarations for commands classes "
.ti -1c
.RI "file \fBKeyence_API\&.h\fP"
.br
.RI "keyence sensors APIs "
.ti -1c
.RI "file \fBlight_barrier\&.hpp\fP"
.br
.RI "endswitch class "
.ti -1c
.RI "file \fBNema17\&.hpp\fP"
.br
.ti -1c
.RI "file \fBNema_8\&.hpp\fP"
.br
.ti -1c
.RI "file \fBReset\&.h\fP"
.br
.RI "class reset for hardware/software reset "
.ti -1c
.RI "file \fBSleep\&.h\fP"
.br
.ti -1c
.RI "file \fBStateManager\&.hpp\fP"
.br
.RI "Manager for internal cpu actions and states\&. "
.ti -1c
.RI "file \fBTimeout\&.hpp\fP"
.br
.RI "timeout lib "
.ti -1c
.RI "file \fBUUID\&.hpp\fP"
.br
.in -1c
