.TH "CmdBuffer.hpp" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdBuffer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ArduinoSTL\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmdBufferObject\fP"
.br
.ti -1c
.RI "class \fBCmdBuffer< BUFFERSIZE >\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBCMDBUFFER_CHAR_PRINTABLE\fP = 0x1F"
.br
.ti -1c
.RI "const uint8_t \fBCMDBUFFER_CHAR_LF\fP = 0x0A"
.br
.ti -1c
.RI "const uint8_t \fBCMDBUFFER_CHAR_CR\fP = 0x0D"
.br
.ti -1c
.RI "const uint8_t \fBCMDBUFFER_CHAR_BS\fP = 0x08"
.br
.ti -1c
.RI "const uint8_t \fBCMDBUFFER_CHAR_DEL\fP = 0x7F"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t CMDBUFFER_CHAR_BS = 0x08"

.PP
Definition at line \fB16\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SS "const uint8_t CMDBUFFER_CHAR_CR = 0x0D"

.PP
Definition at line \fB15\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SS "const uint8_t CMDBUFFER_CHAR_DEL = 0x7F"

.PP
Definition at line \fB17\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SS "const uint8_t CMDBUFFER_CHAR_LF = 0x0A"

.PP
Definition at line \fB14\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SS "const uint8_t CMDBUFFER_CHAR_PRINTABLE = 0x1F"

.PP
Definition at line \fB13\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
