.TH "CmdBuffer< BUFFERSIZE >" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdBuffer< BUFFERSIZE >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdBuffer\&.hpp>\fP
.PP
Inherits \fBCmdBufferObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCmdBuffer\fP ()"
.br
.ti -1c
.RI "virtual void \fBclear\fP ()"
.br
.ti -1c
.RI "virtual uint8_t * \fBgetBuffer\fP ()"
.br
.ti -1c
.RI "virtual size_t \fBgetBufferSize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t BUFFERSIZE>
.br
class CmdBuffer< BUFFERSIZE >"
.PP
Definition at line \fB133\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<size_t BUFFERSIZE> \fBCmdBuffer\fP< BUFFERSIZE >\fB::CmdBuffer\fP ()\fC [inline]\fP"
Cleanup Buffers 
.PP
Definition at line \fB139\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<size_t BUFFERSIZE> virtual void \fBCmdBuffer\fP< BUFFERSIZE >::clear ()\fC [inline]\fP, \fC [virtual]\fP"
Clear buffer with 0x00 
.PP
Implements \fBCmdBufferObject\fP\&.
.PP
Definition at line \fB144\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SS "template<size_t BUFFERSIZE> virtual uint8_t * \fBCmdBuffer\fP< BUFFERSIZE >::getBuffer ()\fC [inline]\fP, \fC [virtual]\fP"
Return a null-terminated ('\\0') string
.PP
\fBReturns\fP
.RS 4
String from Buffer 
.RE
.PP

.PP
Implements \fBCmdBufferObject\fP\&.
.PP
Definition at line \fB149\fP of file \fBCmdBuffer\&.hpp\fP\&.
.SS "template<size_t BUFFERSIZE> virtual size_t \fBCmdBuffer\fP< BUFFERSIZE >::getBufferSize ()\fC [inline]\fP, \fC [virtual]\fP"
Get size of buffer
.PP
\fBReturns\fP
.RS 4
Size of buffer 
.RE
.PP

.PP
Implements \fBCmdBufferObject\fP\&.
.PP
Definition at line \fB154\fP of file \fBCmdBuffer\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
