.TH "CmdCallback< STORESIZE >" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdCallback< STORESIZE >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdCallback\&.hpp>\fP
.PP
Inherits \fB_CmdCallback< STORESIZE, CmdParserString >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<size_t STORESIZE>
.br
class CmdCallback< STORESIZE >"
.PP
Definition at line \fB212\fP of file \fBCmdCallback\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
