.TH "C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include/CmdCallback.hpp" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include/CmdCallback.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'CmdBuffer\&.hpp'\fP
.br
\fC#include 'CmdParser\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmdCallbackObject\fP"
.br
.ti -1c
.RI "class \fB_CmdCallback< STORESIZE, T >\fP"
.br
.ti -1c
.RI "class \fBCmdCallback< STORESIZE >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBCmdCallFunct\fP) (\fBCmdParser\fP *cmdParser)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* CmdCallFunct) (\fBCmdParser\fP *cmdParser)"

.PP
Definition at line \fB22\fP of file \fBCmdCallback\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
