.TH "CmdCallback.hpp" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdCallback.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Thread\&.h'\fP
.br
\fC#include 'ThreadController\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'CmdBuffer\&.hpp'\fP
.br
\fC#include 'CmdParser\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmdCallbackObject\fP"
.br
.ti -1c
.RI "class \fB_CmdCallback< STORESIZE, T >\fP"
.br
.ti -1c
.RI "class \fBCmdCallback< STORESIZE >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBCmdCallFunct\fP) (\fBCmdParser\fP *cmdParser)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ThreadController \fBcontroll\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* CmdCallFunct) (\fBCmdParser\fP *cmdParser)"

.PP
Definition at line \fB24\fP of file \fBCmdCallback\&.hpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "ThreadController controll\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
