.TH "C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/CmdParser.hpp" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/CmdParser.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include 'CmdBuffer\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmdParser\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef const char * \fBCmdParserString\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBCMDPARSER_CHAR_SP\fP = 0x20"
.br
.ti -1c
.RI "const uint8_t \fBCMDPARSER_CHAR_DQ\fP = 0x22"
.br
.ti -1c
.RI "const uint8_t \fBCMDPARSER_CHAR_EQ\fP = 0x3D"
.br
.ti -1c
.RI "const uint16_t \fBCMDPARSER_ERROR\fP = 0xFFFF"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef const char* \fBCmdParserString\fP"

.PP
Definition at line \fB28\fP of file \fBCmdParser\&.hpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const uint8_t CMDPARSER_CHAR_DQ = 0x22"

.PP
Definition at line \fB21\fP of file \fBCmdParser\&.hpp\fP\&.
.SS "const uint8_t CMDPARSER_CHAR_EQ = 0x3D"

.PP
Definition at line \fB22\fP of file \fBCmdParser\&.hpp\fP\&.
.SS "const uint8_t CMDPARSER_CHAR_SP = 0x20"

.PP
Definition at line \fB20\fP of file \fBCmdParser\&.hpp\fP\&.
.SS "const uint16_t CMDPARSER_ERROR = 0xFFFF"

.PP
Definition at line \fB23\fP of file \fBCmdParser\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
