.TH "CmdPatternClasses.h" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdPatternClasses.h \- interface Command &\fBInvoker\fP and Classes Definition here  

.SH SYNOPSIS
.br
.PP
\fC#include 'Alignment\&.hpp'\fP
.br
\fC#include 'Reset\&.h'\fP
.br
\fC#include 'Sleep\&.h'\fP
.br
\fC#include 'UUID\&.hpp'\fP
.br
\fC#include 'StateManager\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBICommand\fP"
.br
.ti -1c
.RI "class \fBgetUUID\fP"
.br
.ti -1c
.RI "class \fBsetUUID\fP"
.br
.ti -1c
.RI "class \fBResetDevice\fP"
.br
.ti -1c
.RI "class \fBSleepDevice\fP"
.br
.ti -1c
.RI "class \fBEnableMotorCmd\fP"
.br
.ti -1c
.RI "class \fBgetMotorCmd\fP"
.br
.ti -1c
.RI "class \fBgetMotorSpeedCmd\fP"
.br
.ti -1c
.RI "class \fBgetMotorDirectionCmd\fP"
.br
.ti -1c
.RI "class \fBgetMotorDelayCmd\fP"
.br
.ti -1c
.RI "class \fBsetMotorCmd\fP"
.br
.ti -1c
.RI "class \fBsetMotorSpeedCmd\fP"
.br
.ti -1c
.RI "class \fBsetMotorDirectionCmd\fP"
.br
.ti -1c
.RI "class \fBsetMotorDelayCmd\fP"
.br
.ti -1c
.RI "class \fBMoveMotorCmd\fP"
.br
.ti -1c
.RI "class \fBMoveMotorUpCmd\fP"
.br
.ti -1c
.RI "class \fBMoveMotorDownCmd\fP"
.br
.ti -1c
.RI "class \fBRotateMotorCmd\fP"
.br
.ti -1c
.RI "class \fBRotateMotorClkCmd\fP"
.br
.ti -1c
.RI "class \fBRotateMotorCclkCmd\fP"
.br
.ti -1c
.RI "class \fBgetSensorCmd\fP"
.br
.ti -1c
.RI "class \fBgetSensorValueCmd\fP"
.br
.ti -1c
.RI "class \fBFirmwareUnit\fP"
.br
.ti -1c
.RI "class \fBCalibrateCmd\fP"
.br
.ti -1c
.RI "class \fBInvoker\fP"
.br
.ti -1c
.RI "class \fBFirmInvoker\fP"
.br
.ti -1c
.RI "class \fBMotorInvoker\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
interface Command &\fBInvoker\fP and Classes Definition here 


.PP
\fBAuthor\fP
.RS 4
sami dhiab (sami@theion.de) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-18
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBCmdPatternClasses\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
