.TH "CmdPatternCallbacks.cpp" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdPatternCallbacks.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CmdPatternCallbacks\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_help\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBdisplay_help_get\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBdisplay_help_set\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBdisplay_help_move\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBdisplay_help_undo\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBdisplay_help_reset\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBdisplay_help_sleep\fP ()"
.br
.RI "display help "
.ti -1c
.RI "void \fBget_help\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "display help "
.ti -1c
.RI "void \fBget_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "callback cmd "
.ti -1c
.RI "void \fBset_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "callback cmd "
.ti -1c
.RI "void \fBmove_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "callback cmd "
.ti -1c
.RI "void \fBrotate_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "callback cmd "
.ti -1c
.RI "void \fBcalibrate_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "calibrate cmd using invoker "
.ti -1c
.RI "void \fBreset_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "reset device "
.ti -1c
.RI "void \fBsleep_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "reset device "
.ti -1c
.RI "void \fBundo_cmd\fP (\fBCmdParser\fP *\fBmyParser\fP)"
.br
.RI "undo last command by calling undo(), then remove it from stack "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void calibrate_cmd (\fBCmdParser\fP * myParser)"

.PP
calibrate cmd using invoker 
.PP
\fBParameters\fP
.RS 4
\fImyParser\fP 
.RE
.PP

.PP
Definition at line \fB318\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB16\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help_get ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help_move ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help_reset ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help_set ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB36\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help_sleep ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB69\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void display_help_undo ()"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void get_cmd (\fBCmdParser\fP * myParser)"

.PP
callback cmd 
.PP
\fBParameters\fP
.RS 4
\fImy\fP cmdParser 
.RE
.PP

.PP
Definition at line \fB98\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void get_help (\fBCmdParser\fP * myParser)"

.PP
display help 
.PP
\fBParameters\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line \fB76\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void move_cmd (\fBCmdParser\fP * myParser)"

.PP
callback cmd 
.PP
\fBParameters\fP
.RS 4
\fImy\fP cmdParser 
.RE
.PP

.PP
Definition at line \fB242\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void reset_cmd (\fBCmdParser\fP * myParser)"

.PP
reset device 
.PP
\fBParameters\fP
.RS 4
\fImyParser\fP 
.RE
.PP

.PP
Definition at line \fB331\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void rotate_cmd (\fBCmdParser\fP * myParser)"

.PP
callback cmd 
.PP
\fBParameters\fP
.RS 4
\fImy\fP cmdParser 
.RE
.PP

.PP
Definition at line \fB293\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void set_cmd (\fBCmdParser\fP * myParser)"

.PP
callback cmd 
.PP
\fBParameters\fP
.RS 4
\fImy\fP cmdParser 
.RE
.PP

.PP
Definition at line \fB173\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void sleep_cmd (\fBCmdParser\fP * myParser)"

.PP
reset device 
.PP
\fBParameters\fP
.RS 4
\fImyParser\fP 
.RE
.PP

.PP
Definition at line \fB341\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SS "void undo_cmd (\fBCmdParser\fP * myParser)"

.PP
undo last command by calling undo(), then remove it from stack undo last command by calling undo();, then remove it from stack
.PP
\fBParameters\fP
.RS 4
\fImyParser\fP 
.RE
.PP

.PP
Definition at line \fB351\fP of file \fBCmdPatternCallbacks\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
