.TH "ComHandler.cpp" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComHandler.cpp \- This Class handles serial communication layer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ComHandler\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
This Class handles serial communication layer\&. 


.PP
\fBAuthor\fP
.RS 4
sami dhiab (sami@theion.de) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.3 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-13
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBComHandler\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
