.TH "C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Configs.h" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Configs.h \- Place the definition of Macros here like pins, enumerate and so on\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ArduinoSTL\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP"
.br
.ti -1c
.RI "#define \fBUSBPORT\fP   Serial"
.br
.ti -1c
.RI "#define \fBBAUDRATE\fP   115200"
.br
.ti -1c
.RI "#define \fBPIN_OUTPUT_RESET\fP   50"
.br
.ti -1c
.RI "#define \fBInterruptSleepPin\fP   32"
.br
.ti -1c
.RI "#define \fBTIMEOUT\fP   false"
.br
.ti -1c
.RI "#define \fBSTEP_DELAY\fP   20"
.br
.ti -1c
.RI "#define \fBSTEP_DELAY_PRINTHEAD_MOTOR\fP   2000"
.br
.ti -1c
.RI "#define \fBXMs1_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBXMs2_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBXMs3_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBXDir_pin\fP   5"
.br
.ti -1c
.RI "#define \fBXEnable_pin\fP   8"
.br
.ti -1c
.RI "#define \fBXStep_pin\fP   2"
.br
.ti -1c
.RI "#define \fBYMs1_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBYMs2_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBYMs3_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBYDir_pin\fP   6"
.br
.ti -1c
.RI "#define \fBYEnable_pin\fP   8"
.br
.ti -1c
.RI "#define \fBYStep_pin\fP   3"
.br
.ti -1c
.RI "#define \fBZMs1_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBZMs2_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBZMs3_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBZDir_pin\fP   7"
.br
.ti -1c
.RI "#define \fBZEnable_pin\fP   8"
.br
.ti -1c
.RI "#define \fBZStep_pin\fP   4"
.br
.ti -1c
.RI "#define \fBPHMs1_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBPHMs2_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBPHMs3_pin\fP   A10"
.br
.ti -1c
.RI "#define \fBPHDir_pin\fP   A9"
.br
.ti -1c
.RI "#define \fBPHEnable_pin\fP   8"
.br
.ti -1c
.RI "#define \fBPHStep_pin\fP   A8"
.br
.ti -1c
.RI "#define \fBE_X\fP   12"
.br
.ti -1c
.RI "#define \fBE_Y\fP   13"
.br
.ti -1c
.RI "#define \fBE_Z\fP   A3"
.br
.ti -1c
.RI "#define \fBLB_X\fP   9"
.br
.ti -1c
.RI "#define \fBLB_Y\fP   10"
.br
.ti -1c
.RI "#define \fBLB_Z\fP   11"
.br
.ti -1c
.RI "#define \fBE_Emergency\fP   A12"
.br
.ti -1c
.RI "#define \fBkeyence\fP"
.br
.ti -1c
.RI "#define \fBKEYENCE_SERIAL_HANDLER\fP   Serial1"
.br
.ti -1c
.RI "#define \fBKEYENCE_SERIAL_BAUDRATE\fP   115200"
.br
.ti -1c
.RI "#define \fBXSensorHead\fP   1"
.br
.ti -1c
.RI "#define \fBYSensorHead\fP   2"
.br
.ti -1c
.RI "#define \fBZSensorHead\fP   3"
.br
.ti -1c
.RI "#define \fBup\fP   1"
.br
.ti -1c
.RI "#define \fBdown\fP   0"
.br
.ti -1c
.RI "#define \fBon\fP   0"
.br
.ti -1c
.RI "#define \fBoff\fP   1"
.br
.ti -1c
.RI "#define \fBclk\fP   1"
.br
.ti -1c
.RI "#define \fBcclk\fP   0"
.br
.ti -1c
.RI "#define \fBMotorLength\fP   31\&.27"
.br
.ti -1c
.RI "#define \fBLeadScrewLEngth\fP   95"
.br
.ti -1c
.RI "#define \fBLinear_travel_per_step\fP   0\&.006"
.br
.ti -1c
.RI "#define \fBAngle_per_step\fP   1\&.8"
.br
.ti -1c
.RI "#define \fBInclinationPH\fP   20"
.br
.ti -1c
.RI "#define \fBEndeffectorThickness\fP   28"
.br
.ti -1c
.RI "#define \fBRodLength\fP   100\&.61"
.br
.ti -1c
.RI "#define \fBMotorSensorHolderThickness\fP   13"
.br
.ti -1c
.RI "#define \fBDISTANCE_PRINTHEAD_PLATFORM\fP   126\&.34"
.br
.ti -1c
.RI "#define \fBSensorThreashold\fP   0\&.4"
.br
.ti -1c
.RI "#define \fBSensorThickness\fP   0"
.br
.ti -1c
.RI "#define \fBAllowedPath\fP   \fBLeadScrewLEngth\fP\-(\fBMotorLength\fP+\fBMotorSensorHolderThickness\fP)"
.br
.ti -1c
.RI "#define \fBRodLength_EndeffectorThickness\fP   \fBRodLength\fP+\fBEndeffectorThickness\fP"
.br
.ti -1c
.RI "#define \fBMicroResolution\fP   0"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBretVal\fP { \fBok\fP = 0, \fBerr\fP = 1 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Place the definition of Macros here like pins, enumerate and so on\&. 


.PP
\fBAuthor\fP
.RS 4
sami dhiab (sami@theion.de) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-02-10
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBConfigs\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AllowedPath   \fBLeadScrewLEngth\fP\-(\fBMotorLength\fP+\fBMotorSensorHolderThickness\fP)"

.PP
Definition at line \fB145\fP of file \fBConfigs\&.h\fP\&.
.SS "#define Angle_per_step   1\&.8"

.PP
Definition at line \fB137\fP of file \fBConfigs\&.h\fP\&.
.SS "#define BAUDRATE   115200"

.PP
Definition at line \fB19\fP of file \fBConfigs\&.h\fP\&.
.SS "#define cclk   0"

.PP
Definition at line \fB108\fP of file \fBConfigs\&.h\fP\&.
.SS "#define clk   1"

.PP
Definition at line \fB107\fP of file \fBConfigs\&.h\fP\&.
.SS "#define DEBUG"

.PP
Definition at line \fB17\fP of file \fBConfigs\&.h\fP\&.
.SS "#define DISTANCE_PRINTHEAD_PLATFORM   126\&.34"

.PP
Definition at line \fB142\fP of file \fBConfigs\&.h\fP\&.
.SS "#define down   0"

.PP
Definition at line \fB104\fP of file \fBConfigs\&.h\fP\&.
.SS "#define E_Emergency   A12"

.PP
Definition at line \fB73\fP of file \fBConfigs\&.h\fP\&.
.SS "#define E_X   12"

.PP
Definition at line \fB63\fP of file \fBConfigs\&.h\fP\&.
.SS "#define E_Y   13"

.PP
Definition at line \fB65\fP of file \fBConfigs\&.h\fP\&.
.SS "#define E_Z   A3"

.PP
Definition at line \fB67\fP of file \fBConfigs\&.h\fP\&.
.SS "#define EndeffectorThickness   28"

.PP
Definition at line \fB139\fP of file \fBConfigs\&.h\fP\&.
.SS "#define InclinationPH   20"

.PP
Definition at line \fB138\fP of file \fBConfigs\&.h\fP\&.
.SS "#define InterruptSleepPin   32"

.PP
Definition at line \fB21\fP of file \fBConfigs\&.h\fP\&.
.SS "#define keyence"

.PP
Definition at line \fB77\fP of file \fBConfigs\&.h\fP\&.
.SS "#define KEYENCE_SERIAL_BAUDRATE   115200"

.PP
Definition at line \fB95\fP of file \fBConfigs\&.h\fP\&.
.SS "#define KEYENCE_SERIAL_HANDLER   Serial1"

.PP
Definition at line \fB93\fP of file \fBConfigs\&.h\fP\&.
.SS "#define LB_X   9"

.PP
Definition at line \fB69\fP of file \fBConfigs\&.h\fP\&.
.SS "#define LB_Y   10"

.PP
Definition at line \fB70\fP of file \fBConfigs\&.h\fP\&.
.SS "#define LB_Z   11"

.PP
Definition at line \fB71\fP of file \fBConfigs\&.h\fP\&.
.SS "#define LeadScrewLEngth   95"

.PP
Definition at line \fB135\fP of file \fBConfigs\&.h\fP\&.
.SS "#define Linear_travel_per_step   0\&.006"

.PP
Definition at line \fB136\fP of file \fBConfigs\&.h\fP\&.
.SS "#define MicroResolution   0"

.PP
Definition at line \fB148\fP of file \fBConfigs\&.h\fP\&.
.SS "#define MotorLength   31\&.27"

.PP
Definition at line \fB134\fP of file \fBConfigs\&.h\fP\&.
.SS "#define MotorSensorHolderThickness   13"

.PP
Definition at line \fB141\fP of file \fBConfigs\&.h\fP\&.
.SS "#define off   1"

.PP
Definition at line \fB106\fP of file \fBConfigs\&.h\fP\&.
.SS "#define on   0"

.PP
Definition at line \fB105\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PHDir_pin   A9"

.PP
Definition at line \fB58\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PHEnable_pin   8"

.PP
Definition at line \fB59\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PHMs1_pin   A10"

.PP
Definition at line \fB55\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PHMs2_pin   A10"

.PP
Definition at line \fB56\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PHMs3_pin   A10"

.PP
Definition at line \fB57\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PHStep_pin   A8"

.PP
Definition at line \fB60\fP of file \fBConfigs\&.h\fP\&.
.SS "#define PIN_OUTPUT_RESET   50"

.PP
Definition at line \fB20\fP of file \fBConfigs\&.h\fP\&.
.SS "#define RodLength   100\&.61"

.PP
Definition at line \fB140\fP of file \fBConfigs\&.h\fP\&.
.SS "#define RodLength_EndeffectorThickness   \fBRodLength\fP+\fBEndeffectorThickness\fP"

.PP
Definition at line \fB146\fP of file \fBConfigs\&.h\fP\&.
.SS "#define SensorThickness   0"

.PP
Definition at line \fB144\fP of file \fBConfigs\&.h\fP\&.
.SS "#define SensorThreashold   0\&.4"

.PP
Definition at line \fB143\fP of file \fBConfigs\&.h\fP\&.
.SS "#define STEP_DELAY   20"

.PP
Definition at line \fB31\fP of file \fBConfigs\&.h\fP\&.
.SS "#define STEP_DELAY_PRINTHEAD_MOTOR   2000"

.PP
Definition at line \fB32\fP of file \fBConfigs\&.h\fP\&.
.SS "#define TIMEOUT   false"

.PP
Definition at line \fB25\fP of file \fBConfigs\&.h\fP\&.
.SS "#define up   1"

.PP
Definition at line \fB103\fP of file \fBConfigs\&.h\fP\&.
.SS "#define USBPORT   Serial"

.PP
Definition at line \fB18\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XDir_pin   5"

.PP
Definition at line \fB37\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XEnable_pin   8"

.PP
Definition at line \fB38\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XMs1_pin   A10"

.PP
Definition at line \fB34\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XMs2_pin   A10"

.PP
Definition at line \fB35\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XMs3_pin   A10"

.PP
Definition at line \fB36\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XSensorHead   1"

.PP
Definition at line \fB97\fP of file \fBConfigs\&.h\fP\&.
.SS "#define XStep_pin   2"

.PP
Definition at line \fB39\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YDir_pin   6"

.PP
Definition at line \fB44\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YEnable_pin   8"

.PP
Definition at line \fB45\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YMs1_pin   A10"

.PP
Definition at line \fB41\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YMs2_pin   A10"

.PP
Definition at line \fB42\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YMs3_pin   A10"

.PP
Definition at line \fB43\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YSensorHead   2"

.PP
Definition at line \fB98\fP of file \fBConfigs\&.h\fP\&.
.SS "#define YStep_pin   3"

.PP
Definition at line \fB46\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZDir_pin   7"

.PP
Definition at line \fB51\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZEnable_pin   8"

.PP
Definition at line \fB52\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZMs1_pin   A10"

.PP
Definition at line \fB48\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZMs2_pin   A10"

.PP
Definition at line \fB49\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZMs3_pin   A10"

.PP
Definition at line \fB50\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZSensorHead   3"

.PP
Definition at line \fB99\fP of file \fBConfigs\&.h\fP\&.
.SS "#define ZStep_pin   4"

.PP
Definition at line \fB53\fP of file \fBConfigs\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBretVal\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIok \fP\fP
.TP
\fB\fIerr \fP\fP
.PP
Definition at line \fB151\fP of file \fBConfigs\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
