.TH "getMotorSpeedCmd" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getMotorSpeedCmd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdPatternClasses\&.h>\fP
.PP
Inherits \fBICommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMotorSpeedCmd\fP (\fBNema8\fP &motor)"
.br
.ti -1c
.RI "virtual void \fBexecute\fP ()"
.br
.ti -1c
.RI "virtual void \fBundo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB116\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "getMotorSpeedCmd::getMotorSpeedCmd (\fBNema8\fP & motor)\fC [inline]\fP"

.PP
Definition at line \fB121\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void getMotorSpeedCmd::execute ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB122\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "virtual void getMotorSpeedCmd::undo ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB126\fP of file \fBCmdPatternClasses\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
