.TH "getMotorDirectionCmd" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getMotorDirectionCmd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdPatternClasses\&.h>\fP
.PP
Inherits \fBICommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMotorDirectionCmd\fP (\fBNema8\fP &motor)"
.br
.ti -1c
.RI "virtual void \fBexecute\fP ()"
.br
.ti -1c
.RI "virtual void \fBundo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB130\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "getMotorDirectionCmd::getMotorDirectionCmd (\fBNema8\fP & motor)\fC [inline]\fP"

.PP
Definition at line \fB135\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void getMotorDirectionCmd::execute ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB136\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "virtual void getMotorDirectionCmd::undo ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB139\fP of file \fBCmdPatternClasses\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
