.TH "ICommand" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICommand
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdPatternClasses\&.h>\fP
.PP
Inherited by \fBCalibrateCmd\fP, \fBEnableMotorCmd\fP, \fBMoveMotorCmd\fP, \fBMoveMotorDownCmd\fP, \fBMoveMotorUpCmd\fP, \fBResetDevice\fP, \fBRotateMotorCclkCmd\fP, \fBRotateMotorClkCmd\fP, \fBRotateMotorCmd\fP, \fBSleepDevice\fP, \fBgetMotorCmd\fP, \fBgetMotorDelayCmd\fP, \fBgetMotorDirectionCmd\fP, \fBgetMotorSpeedCmd\fP, \fBgetSensorCmd\fP, \fBgetSensorValueCmd\fP, \fBgetUUID\fP, \fBsetMotorCmd\fP, \fBsetMotorDelayCmd\fP, \fBsetMotorDirectionCmd\fP, \fBsetMotorSpeedCmd\fP, and \fBsetUUID\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ICommand\fP ()"
.br
.ti -1c
.RI "virtual void \fBexecute\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBundo\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ICommand::~ICommand ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB23\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ICommand::execute ()\fC [pure virtual]\fP"

.PP
Implemented in \fBgetUUID\fP, \fBsetUUID\fP, \fBResetDevice\fP, \fBSleepDevice\fP, \fBEnableMotorCmd\fP, \fBgetMotorCmd\fP, \fBgetMotorSpeedCmd\fP, \fBgetMotorDirectionCmd\fP, \fBgetMotorDelayCmd\fP, \fBsetMotorCmd\fP, \fBsetMotorSpeedCmd\fP, \fBsetMotorDirectionCmd\fP, \fBsetMotorDelayCmd\fP, \fBMoveMotorCmd\fP, \fBMoveMotorUpCmd\fP, \fBMoveMotorDownCmd\fP, \fBRotateMotorCmd\fP, \fBRotateMotorClkCmd\fP, \fBRotateMotorCclkCmd\fP, \fBgetSensorCmd\fP, \fBgetSensorValueCmd\fP, and \fBCalibrateCmd\fP\&.
.SS "virtual void ICommand::undo ()\fC [pure virtual]\fP"

.PP
Implemented in \fBgetUUID\fP, \fBsetUUID\fP, \fBResetDevice\fP, \fBSleepDevice\fP, \fBEnableMotorCmd\fP, \fBgetMotorCmd\fP, \fBgetMotorSpeedCmd\fP, \fBgetMotorDirectionCmd\fP, \fBgetMotorDelayCmd\fP, \fBsetMotorCmd\fP, \fBsetMotorSpeedCmd\fP, \fBsetMotorDirectionCmd\fP, \fBsetMotorDelayCmd\fP, \fBMoveMotorCmd\fP, \fBMoveMotorUpCmd\fP, \fBMoveMotorDownCmd\fP, \fBRotateMotorCmd\fP, \fBRotateMotorClkCmd\fP, \fBRotateMotorCclkCmd\fP, \fBgetSensorCmd\fP, \fBgetSensorValueCmd\fP, and \fBCalibrateCmd\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
