.TH "Invoker" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Invoker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdPatternClasses\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Invoker\fP ()"
.br
.ti -1c
.RI "void \fBSetOnStart\fP (\fBICommand\fP *command)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBSetOnfinish\fP (\fBICommand\fP *command)"
.br
.ti -1c
.RI "void \fBfinish\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB390\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Invoker::~Invoker ()\fC [inline]\fP"

.PP
Definition at line \fB397\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Invoker::finish ()\fC [inline]\fP"

.PP
Definition at line \fB413\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "void Invoker::SetOnfinish (\fBICommand\fP * command)\fC [inline]\fP"

.PP
Definition at line \fB410\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "void Invoker::SetOnStart (\fBICommand\fP * command)\fC [inline]\fP"

.PP
Definition at line \fB401\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "void Invoker::start ()\fC [inline]\fP"

.PP
Definition at line \fB404\fP of file \fBCmdPatternClasses\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
