.TH "C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Keyence_API.h" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Keyence_API.h \- keyence sensors APIs  

.SH SYNOPSIS
.br
.PP
\fC#include <ArduinoSTL\&.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'Configs\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKeyence_base\fP"
.br
.ti -1c
.RI "class \fBKeyence_rs232_interface\fP"
.br
.ti -1c
.RI "class \fBKeyence_ethernet_interface\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCR\fP   '\\r'"
.br
.ti -1c
.RI "#define \fBLF\fP   '\\n'"
.br
.in -1c
.SH "Detailed Description"
.PP 
keyence sensors APIs 


.PP
\fBAuthor\fP
.RS 4
sami dhiab (sami@theion.de) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-04-06
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBKeyence_API\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CR   '\\r'"

.PP
Definition at line \fB22\fP of file \fBKeyence_API\&.h\fP\&.
.SS "#define LF   '\\n'"

.PP
Definition at line \fB23\fP of file \fBKeyence_API\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
