.TH "Keyence_base" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keyence_base
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Keyence_API\&.h>\fP
.PP
Inherited by \fBKeyence_ethernet_interface\fP, and \fBKeyence_rs232_interface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBfindCommand\fP (String &command, std::map< String, String > &CommandMap)"
.br
.ti -1c
.RI "virtual double \fBgetValueSingleOutputHead\fP (int output_head_Nr)=0"
.br
.ti -1c
.RI "virtual double * \fBgetValueMultipleOutputHead\fP (String \fBHeadsArray\fP)=0"
.br
.ti -1c
.RI "virtual double * \fBgetValueOutputHeadAll\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetGeneralMode\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetCommunicationMode\fP ()=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlistHeads\fP ()"
.br
.ti -1c
.RI "template<typename T > static void \fBprintVectorElements\fP (std::vector< T > &vec)"
.br
.ti -1c
.RI "template<typename A > static void \fBprintArrayElements\fP (A &array)"
.br
.ti -1c
.RI "template<typename A , typename V > static void \fBtransformArrayToVector\fP (A &array, std::vector< V > &vector)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBRawCommands\fP [9] = {'Q0','R0','MS,','MS,01','MS,02','MS,03','MM,1110000000000','MM,','MA'}"
.br
.ti -1c
.RI "std::map< String, String > \fBcommands\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::vector< int > \fBNumUsedHeads\fP"
.br
.ti -1c
.RI "static int \fBHeadsCount\fP = 0"
.br
.ti -1c
.RI "static int \fBHeadsArray\fP [12]"
.br
.ti -1c
.RI "static double * \fBLookUpValues\fP = new double[\fBKeyence_base::HeadsCount\fP]{ 0 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB64\fP of file \fBKeyence_API\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "String Keyence_base::findCommand (String & command, std::map< String, String > & CommandMap)"

.PP
Definition at line \fB42\fP of file \fBKeyence_API\&.cpp\fP\&.
.SS "virtual double * Keyence_base::getValueMultipleOutputHead (String HeadsArray)\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyence_rs232_interface\fP\&.
.SS "virtual double * Keyence_base::getValueOutputHeadAll ()\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyence_rs232_interface\fP\&.
.SS "virtual double Keyence_base::getValueSingleOutputHead (int output_head_Nr)\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyence_rs232_interface\fP\&.
.SS "void Keyence_base::listHeads ()\fC [static]\fP"

.PP
Definition at line \fB21\fP of file \fBKeyence_API\&.cpp\fP\&.
.SS "template<typename A > static void Keyence_base::printArrayElements (A & array)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB118\fP of file \fBKeyence_API\&.h\fP\&.
.SS "template<typename T > static void Keyence_base::printVectorElements (std::vector< T > & vec)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBKeyence_API\&.h\fP\&.
.SS "virtual void Keyence_base::setCommunicationMode ()\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyence_rs232_interface\fP\&.
.SS "virtual void Keyence_base::setGeneralMode ()\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyence_rs232_interface\fP\&.
.SS "template<typename A , typename V > static void Keyence_base::transformArrayToVector (A & array, std::vector< V > & vector)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB127\fP of file \fBKeyence_API\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::map<String, String> Keyence_base::commands"
\fBInitial value:\fP
.PP
.nf
{
{"set_communication_mode",RawCommands[0]},
{"set_general_mode",RawCommands[1]},
{"mesure_value_outputN",RawCommands[2]},
{"mesure_value_output1",RawCommands[3]},
{"mesure_value_output2",RawCommands[4]},
{"mesure_value_output3",RawCommands[5]},
{"mesure_value_multiple123",RawCommands[6]},
{"mesure_value_multipleN",RawCommands[7]},
{"mesure_value_All",RawCommands[8]},
}
.fi
.PP
Definition at line \fB70\fP of file \fBKeyence_API\&.h\fP\&.
.SS "int Keyence_base::HeadsArray\fC [static]\fP"

.PP
Definition at line \fB87\fP of file \fBKeyence_API\&.h\fP\&.
.SS "int Keyence_base::HeadsCount = 0\fC [static]\fP"

.PP
Definition at line \fB85\fP of file \fBKeyence_API\&.h\fP\&.
.SS "double * Keyence_base::LookUpValues = new double[\fBKeyence_base::HeadsCount\fP]{ 0 }\fC [static]\fP"

.PP
Definition at line \fB89\fP of file \fBKeyence_API\&.h\fP\&.
.SS "std::vector< int > Keyence_base::NumUsedHeads\fC [static]\fP"

.PP
Definition at line \fB83\fP of file \fBKeyence_API\&.h\fP\&.
.SS "String Keyence_base::RawCommands[9] = {'Q0','R0','MS,','MS,01','MS,02','MS,03','MM,1110000000000','MM,','MA'}"

.PP
Definition at line \fB68\fP of file \fBKeyence_API\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
