.TH "light_barrier.hpp" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
light_barrier.hpp \- endswitch class  

.SH SYNOPSIS
.br
.PP
\fC#include <ArduinoSTL\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlightBarrier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
endswitch class 


.PP
\fBAuthor\fP
.RS 4
sami dhiab (sami@theion.de) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-02-11
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBlight_barrier\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
