.TH "Nema8" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nema8 \- child class nema8 from parent class stepper driver \fBa4988\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Nema_8\&.hpp>\fP
.PP
Inherits \fBa4988\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNema8\fP (int \fBmotor_steps\fP, int \fBms1_pin\fP, int \fBms2_pin\fP, int \fBms3_pin\fP, int \fBdir_pin\fP, int \fBenable_pin\fP, int \fBstep_pin\fP, bool \fBdirection\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
child class nema8 from parent class stepper driver \fBa4988\fP 
.PP
Definition at line \fB19\fP of file \fBNema_8\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Nema8::Nema8 (int motor_steps, int ms1_pin, int ms2_pin, int ms3_pin, int dir_pin, int enable_pin, int step_pin, bool direction)\fC [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBNema_8\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
