.TH "C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Nema17.hpp" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Nema17.hpp
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
sami dhiab (sami@theion.de) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-02-11
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBNema17\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
