.TH "C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include/Reset.h" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include/Reset.h \- class reset for hardware/software reset  

.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'EndSwitch\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResetHardware\fP"
.br
.RI "reset device: hw reset by connecting output pin to reset input pin and set to high or sw reset by calling resetFunc() internally\&. "
.in -1c
.SH "Detailed Description"
.PP 
class reset for hardware/software reset 


.PP
\fBAuthor\fP
.RS 4
sami dhiab (you@domain.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-16
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
Definition in file \fBReset\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
