.TH "ResetHardware" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResetHardware \- reset device: hw reset by connecting output pin to reset input pin and set to high or sw reset by calling resetFunc() internally\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Reset\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResetHardware\fP (int resetOutPin)"
.br
.ti -1c
.RI "void \fBhard_reset\fP ()"
.br
.ti -1c
.RI "void \fBsoft_reset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
reset device: hw reset by connecting output pin to reset input pin and set to high or sw reset by calling resetFunc() internally\&. 
.PP
Definition at line \fB19\fP of file \fBReset\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ResetHardware::ResetHardware (int resetOutPin)\fC [inline]\fP"

.PP
Definition at line \fB26\fP of file \fBReset\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ResetHardware::hard_reset ()\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBReset\&.h\fP\&.
.SS "void ResetHardware::soft_reset ()\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBReset\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
