.TH "RotateMotorCmd" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RotateMotorCmd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdPatternClasses\&.h>\fP
.PP
Inherits \fBICommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotateMotorCmd\fP (\fBNema8\fP &motor, int val)"
.br
.ti -1c
.RI "virtual void \fBexecute\fP ()"
.br
.ti -1c
.RI "virtual void \fBundo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB278\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RotateMotorCmd::RotateMotorCmd (\fBNema8\fP & motor, int val)\fC [inline]\fP"

.PP
Definition at line \fB284\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void RotateMotorCmd::execute ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB285\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "virtual void RotateMotorCmd::undo ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB289\fP of file \fBCmdPatternClasses\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
