.TH "setUUID" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setUUID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CmdPatternClasses\&.h>\fP
.PP
Inherits \fBICommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUUID\fP (\fBUUID_MANAGER\fP &idObj, String uuid)"
.br
.ti -1c
.RI "virtual void \fBexecute\fP ()"
.br
.ti -1c
.RI "virtual void \fBundo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB44\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "setUUID::setUUID (\fBUUID_MANAGER\fP & idObj, String uuid)\fC [inline]\fP"

.PP
Definition at line \fB50\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void setUUID::execute ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB51\fP of file \fBCmdPatternClasses\&.h\fP\&.
.SS "virtual void setUUID::undo ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBICommand\fP\&.
.PP
Definition at line \fB56\fP of file \fBCmdPatternClasses\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
