.TH "C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Sleep.h" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firmware_design_template/include/Sleep.h
.SH SYNOPSIS
.br
.PP
\fC#include <avr/sleep\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSleepHardware\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
