.TH "SleepHardware" 3 "Fri May 27 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SleepHardware
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sleep\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSleepHardware\fP (int interruptPin)"
.br
.ti -1c
.RI "void \fBSleep\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBwakeUp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Author:Ab Kurk version: 1\&.0 date: 24/01/2018 Description: This sketch is part of the beginners guide to putting your Arduino to sleep tutorial\&. It is to demonstrate how to put your arduino into deep sleep and how to wake it up\&. Link To Tutorial http://www.thearduinomakerman.info/blog/2018/1/24/guide-to-arduino-sleep-mode 
.PP
Definition at line \fB14\fP of file \fBSleep\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SleepHardware::SleepHardware (int interruptPin)\fC [inline]\fP"

.PP
Definition at line \fB18\fP of file \fBSleep\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SleepHardware::Sleep ()\fC [inline]\fP"

.PP
Definition at line \fB24\fP of file \fBSleep\&.h\fP\&.
.SS "static void SleepHardware::wakeUp ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB35\fP of file \fBSleep\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
