.TH "TaskTimer" 3 "Tue May 24 2022" "Version 0.2" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskTimer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timeout\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTaskTimer\fP (unsigned int \fBinterval\fP, unsigned long \fBtimer\fP, bool \fBmillisec\fP)"
.br
.ti -1c
.RI "template<typename Function > void \fBtaskSchedule\fP (Function func)"
.br
.ti -1c
.RI "void \fBtimeStop\fP ()"
.br
.ti -1c
.RI "void \fBprintTimerValue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBinterval\fP"
.br
.ti -1c
.RI "unsigned long \fBtimer\fP =0"
.br
.ti -1c
.RI "bool \fBmillisec\fP =true"
.br
.ti -1c
.RI "unsigned long(* \fBInternalClock\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBTimeout\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TaskTimer::TaskTimer (unsigned int interval, unsigned long timer, bool millisec)\fC [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBTimeout\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TaskTimer::printTimerValue ()\fC [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBTimeout\&.hpp\fP\&.
.SS "template<typename Function > void TaskTimer::taskSchedule (Function func)\fC [inline]\fP"

.PP
Definition at line \fB33\fP of file \fBTimeout\&.hpp\fP\&.
.SS "void TaskTimer::timeStop ()\fC [inline]\fP"

.PP
Definition at line \fB41\fP of file \fBTimeout\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned long(* TaskTimer::InternalClock) (void)"

.PP
Definition at line \fB20\fP of file \fBTimeout\&.hpp\fP\&.
.SS "unsigned int TaskTimer::interval"

.PP
Definition at line \fB17\fP of file \fBTimeout\&.hpp\fP\&.
.SS "bool TaskTimer::millisec =true"

.PP
Definition at line \fB19\fP of file \fBTimeout\&.hpp\fP\&.
.SS "unsigned long TaskTimer::timer =0"

.PP
Definition at line \fB18\fP of file \fBTimeout\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
