.TH "C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include/UUID.hpp" 3 "Thu May 19 2022" "Version 0.1" "Firmware Design Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SamiDhiab/Theion_Repos/firm_Alignment_PrintHead/include/UUID.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <EEPROM\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUUID_MANAGER\fP"
.br
.RI "Class for managing UUID, construct a new uuid manager object by passing the name to constructor to automaticly point to the specific id\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBusing_serial_stream\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define using_serial_stream"

.PP
Definition at line \fB13\fP of file \fBUUID\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Firmware Design Template from the source code\&.
